Repository Nostralys-Studio/FrostfallSaga, pull requests merged in 2024-05, with the labels that each got.

#1 feat(github-action): from gitlab-ci to github actions FFS-159
  .github/workflows/main.yml
  .gitlab-ci.yml
  ci/before_script.sh
  ci/build.sh
  ci/docker_build.sh
  ci/docker_test.sh
  ci/get_activation_file.sh
  ci/nunit-transforms/LICENSE.txt
  ci/nunit-transforms/nunit3-junit.xslt
  ci/test.sh
Labels: enhancement

#3 Feat/ffs 159 from gitlab to GitHub
  README.md
Labels: enhancement

#4 feat(gh-workflows): workflow splitted to facilitate usage and preserv…
  .github/workflows/build-webgl-and-deploy.yml
  .github/workflows/build-windows.yml
  .github/workflows/test-build-and-deploy.yml
  .github/workflows/test.yml
  Assets/Scripts/Editor.meta
  Assets/Scripts/Editor/BuildCommand.cs
  Assets/Scripts/Editor/BuildCommand.cs.meta
Labels: enhancement

#7 feat(test.yml): upload latest coverage results on pages
  .github/workflows/test.yml
Labels: ci/cd

#8 feat(build-webgl-and-deploy.yml): target folder name updated to inclu…
  .github/workflows/build-webgl-and-deploy.yml
  .github/workflows/test-build-and-deploy.yml
Labels: ci/cd

#9 feat: template tests added for HexMetrics + file structure refactored
  .github/workflows/test.yml
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  Assets/Art/Audio.meta
  Assets/Art/Audio/Musics.meta
  Assets/Art/Audio/SFX.meta
  Assets/AssetsPackages/PolygonParticleFX.meta
  Assets/AssetsPackages/PolygonVikings.meta
  Assets/Code/Scripts/Cell/Cell.cs
  Assets/Code/Scripts/Cell/CellVisual.cs
  Assets/Code/Scripts/Controller/MouseController.cs
  Assets/Code/Scripts/HexGrid/HexGrid.cs
  Assets/Code/Scripts/HexGrid/HexGridGenerator.cs
  Assets/Code/Scripts/HexGrid/HexMetrics.cs
  Assets/Code/Scripts/Scripts.asmdef
  Assets/Code/Scripts/Scripts.asmdef.meta
  Assets/Code/Tests.meta
  Assets/Code/Tests/EditMode.meta
  Assets/Code/Tests/EditMode/EditMode.asmdef
  Assets/Code/Tests/EditMode/EditMode.asmdef.meta
  Assets/Code/Tests/EditMode/HexGrid.meta
  Assets/Code/Tests/EditMode/HexGrid/HexMetricsTests.cs
  Assets/Code/Tests/EditMode/HexGrid/HexMetricsTests.cs.meta
  Assets/Code/Tests/PlayMode.meta
  Assets/Code/Tests/PlayMode/PlayMode.asmdef
  Assets/Code/Tests/PlayMode/PlayMode.asmdef.meta
  Assets/Tests/DummyTest.cs
  Assets/Tests/Tests.asmdef
  ProjectSettings/EditorSettings.asset
Labels: refactoring, tests

#12 feat(effects): ffs-100-create-effects
  Assets/Code/Scripts/Effect/AEffect.cs
  Assets/Code/Scripts/Effect/AEffect.cs.meta
  Assets/Code/Scripts/Effect/DamageEffect.cs
  Assets/Code/Scripts/Effect/DamageEffect.cs.meta
  Assets/Code/Scripts/Effect/HealEffect.cs
  Assets/Code/Scripts/Effect/HealEffect.cs.meta
Labels: feature

#15 fix(editor): excluded editor scripts from build
  Assets/Code/Scripts/Editor.meta
  Assets/Code/Scripts/Editor/FrostfallSaga.FFSEditor.asmdef
  Assets/Code/Scripts/Editor/FrostfallSaga.FFSEditor.asmdef.meta
  Assets/Code/Scripts/Effect/DamageEffect.cs
  Assets/Code/Scripts/Effect/HealEffect.cs
  Assets/Code/Scripts/Fight.meta
  Assets/Code/Scripts/Fight/Effects.meta
  Assets/Code/Scripts/Fight/Effects/AEffect.cs
  Assets/Code/Scripts/Fight/Effects/AEffect.cs.meta
  Assets/Code/Scripts/Fight/Effects/DamageEffect.cs
  Assets/Code/Scripts/Fight/Effects/DamageEffect.cs.meta
  Assets/Code/Scripts/Fight/Effects/HealEffect.cs
  Assets/Code/Scripts/Fight/Effects/HealEffect.cs.meta
  Assets/Code/Scripts/Fight/FrostfallSaga.Fight.asmdef
  Assets/Code/Scripts/Fight/FrostfallSaga.Fight.asmdef.meta
  Assets/Code/Scripts/HexGrid/Cells/Cell.cs
  Assets/Code/Scripts/HexGrid/Cells/CellVisual.cs
  Assets/Code/Scripts/HexGrid/Cells/Editor/CellEditor.cs
  Assets/Code/Scripts/HexGrid/Cells/Editor/FrostfallSaga.Editor.Grid.Cells.asmref
  Assets/Code/Scripts/HexGrid/Cells/Editor/FrostfallSaga.Editor.Grid.Cells.asmref.meta
  Assets/Code/Scripts/HexGrid/ECellOrientation.cs
  Assets/Code/Scripts/HexGrid/ECellOrientation.cs.meta
  Assets/Code/Scripts/HexGrid/Editor/FrostfallSaga.Editor.HexGrid.asmref
  Assets/Code/Scripts/HexGrid/Editor/FrostfallSaga.Editor.HexGrid.asmref.meta
  Assets/Code/Scripts/HexGrid/Editor/HexGridEditor.cs
  Assets/Code/Scripts/HexGrid/Editor/HexGridGeneratorEditor.cs
  Assets/Code/Scripts/HexGrid/HexGrid.cs
  Assets/Code/Scripts/HexGrid/HexGridGenerator.cs
  Assets/Code/Scripts/HexGrid/HexMetrics.cs
  Assets/Level/Scenes/KingdomScene.unity
  Assets/Settings/URP-HighFidelity.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Assets/WSATestCertificate.pfx
  Assets/WSATestCertificate.pfx.meta
  ProjectSettings/BurstAotSettings_WSAPlayer.json
  ProjectSettings/CommonBurstAotSettings.json
  ProjectSettings/ProjectSettings.asset
Labels: bug

#16 feat: updated changes to fit last project refactor
  Assets/Code/Scripts/Core/PriorityQueue.cs
  Assets/Code/Scripts/Core/PriorityQueue.cs.meta
  Assets/Code/Scripts/HexGrid/Cells/Cell.cs
  Assets/Code/Scripts/HexGrid/Cells/Editor/CellEditor.cs
  Assets/Code/Scripts/HexGrid/CellsPathFinding.cs
  Assets/Code/Scripts/HexGrid/CellsPathFinding.cs.meta
  Assets/Code/Scripts/HexGrid/Editor/HexGridGeneratorEditor.cs
  Assets/Code/Scripts/HexGrid/HexGrid.cs
  Assets/Code/Scripts/HexGrid/HexGridGenerator.cs
Labels: feature
