Repository Nostralys-Studio/FrostfallSaga, pull requests merged in 2024-12, with the labels that each got.

#150 fix(WeaponSO): don't compute fighter strengths if no strength defined
  Assets/Code/Scripts/Fight/GameItems/WeaponSO.cs
Labels: bug, tests

#151 fix(FightManager): fighters turn order fixed
  Assets/Code/Scripts/Fight/FightManager.cs
  Assets/Level/Prefabs/EntitiesVisuals/Warrior/Warrior Variant Armed.prefab
  Assets/Level/Prefabs/Fighters/SkeletonFighter.prefab
  Assets/Level/Scenes/FightScene.unity
Labels: bug

#152 feat: name added to EntityConfigurationSO + some content configured f…
  Assets/Art/UI/DiamondSkeletonPortrait.png
  Assets/Art/UI/DiamondSkeletonPortrait.png.meta
  Assets/Code/Scripts/Kingdom/Entities/EntityConfigurationSO.cs
  Assets/Code/Scripts/KingdomToFight/FightersSetupGenerator.cs
  Assets/Level/Scenes/FightScene.unity
  Assets/Resources/ScriptableObjects/Entities/COMPANION1.asset
  Assets/Resources/ScriptableObjects/Entities/COMPANION2.asset
  Assets/Resources/ScriptableObjects/Entities/HERO.asset
  Assets/Resources/ScriptableObjects/Entities/SKELETON.asset
Labels: feature

#161 Refactor/utils
  Assets/Code/Scripts/Core/EEntityID.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/DamageTargetAction.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Checks/CanDamageTargetCheck.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Checks/CanHealTargetCheck.cs
  Assets/Code/Scripts/Fight/Controllers/RandomController.cs
  Assets/Code/Scripts/Fight/FightCells/FightCellAlterations/RandomHeightAlteration.cs
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/Fighter/FighterClassSO.cs
  Assets/Code/Scripts/Fight/FighterSetup.cs
  Assets/Code/Scripts/Fight/FrostfallSaga.Fight.asmdef
  Assets/Code/Scripts/Fight/GameItems/ArmorSO.cs
  Assets/Code/Scripts/Fight/GameItems/WeaponSO.cs
  Assets/Code/Scripts/Fight/Targeter/Targeter.cs
  Assets/Code/Scripts/Fight/UI/EffectsFeedbackController.cs
  Assets/Code/Scripts/Grid/Cells/Cell.cs
  Assets/Code/Scripts/Grid/CellsPathFinding.cs
  Assets/Code/Scripts/Grid/FrostfallSaga.Grid.asmdef
  Assets/Code/Scripts/Grid/HexGridGenerator.cs
  Assets/Code/Scripts/Kingdom/Entities/EntityConfigurationSO.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntitiesGroup.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroupsMovementController.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroupsSpawner/EntitiesGroupsSpawner.cs
  Assets/Code/Scripts/Kingdom/FrostfallSaga.Kingdom.asmdef
  Assets/Code/Scripts/Kingdom/KingdomLoader.cs
  Assets/Code/Scripts/Kingdom/PostFightDataSO.cs
  Assets/Code/Scripts/KingdomToFight/EntityToFighter.cs
  Assets/Code/Scripts/KingdomToFight/FighterConfigurationSO.cs
  Assets/Code/Scripts/KingdomToFight/FightersSetupGenerator.cs
  Assets/Code/Scripts/KingdomToFight/FrostfallSaga.KingdomToFight.asmdef
  Assets/Code/Scripts/Procedural/FrostfallSaga.Procedural.asmdef
  Assets/Code/Scripts/Procedural/PerlinTerrainManager.cs
  Assets/Code/Scripts/Procedural/VoronoiBiomeManager.cs
  Assets/Code/Scripts/Utils.meta
  Assets/Code/Scripts/Utils/FrostfallSaga.Utils.asmdef
  Assets/Code/Scripts/Utils/FrostfallSaga.Utils.asmdef.meta
  Assets/Code/Scripts/Utils/ListOfTypes.cs
  Assets/Code/Scripts/Utils/ListOfTypes.cs.meta
  Assets/Code/Scripts/Utils/PriorityQueue.cs
  Assets/Code/Scripts/Utils/PriorityQueue.cs.meta
  Assets/Code/Scripts/Utils/Randomizer.cs
  Assets/Code/Scripts/Utils/Randomizer.cs.meta
  Assets/Code/Scripts/Utils/RequiredAttribute.cs
  Assets/Code/Scripts/Utils/RequiredAttribute.cs.meta
  Assets/Code/Scripts/Utils/SerializableElementToValue.cs
  Assets/Code/Scripts/Utils/SerializableElementToValue.cs.meta
  Assets/Code/Scripts/Utils/Validator.cs
  Assets/Code/Scripts/Utils/Validator.cs.meta
  Assets/Code/Tests/EditModeTests/CommonTestsHelper.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FightTestsHelper.cs
  Assets/Code/Tests/EditModeTests/HexGrid/Cells/GetNeighborsTests.cs
  Assets/Code/Tests/EditModeTests/HexGrid/Cells/GetShorterPathTests.cs
  Assets/Resources/EditModeTests/ScriptableObjects/TestBiome.asset
  Assets/Resources/EditModeTests/ScriptableObjects/TestBiome.asset.meta
  Assets/Resources/EditModeTests/ScriptableObjects/TestTerrainTypeAccessible.asset
  Assets/Resources/EditModeTests/ScriptableObjects/TestTerrainTypeAccessible.asset.meta
  Assets/Resources/EditModeTests/ScriptableObjects/TestTerrainTypeInaccessible.asset
  Assets/Resources/EditModeTests/ScriptableObjects/TestTerrainTypeInaccessible.asset.meta
Labels: refactoring

#160 Refactor/material highlightable
  Assets/Code/Scripts/GameObjectVisuals/MaterialHighlitable.cs
  Assets/Code/Scripts/GameObjectVisuals/MaterialHighlitable.cs.meta
  Assets/Code/Scripts/Grid/Cells/Cell.cs
  Assets/Code/Scripts/Grid/FrostfallSaga.Grid.asmdef
  Assets/Code/Scripts/Kingdom/FrostfallSaga.Kingdom.asmdef
  Assets/Code/Tests/EditModeTests/CommonTestsHelper.cs
  Assets/Code/Tests/EditModeTests/EditModeTests.asmdef
Labels: refactoring

#163 refactor(EditModeTests): added setup and teardown methods to test
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterHealTests.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterMagicalWithstandTests.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterPhysicalWithstandTests.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterStatusAbilitiesTests.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterUseActiveAbilityTests.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterUseDirectAttackTests.cs
  Assets/Code/Tests/EditModeTests/HexGrid/Cells/GetNeighborsTests.cs
  Assets/Code/Tests/EditModeTests/HexGrid/Cells/GetShorterPathTests.cs
  Assets/Code/Tests/EditModeTests/Kingdom/EntitiesGroupsMovementControllerTests.cs
Labels: refactoring, tests

#165 feat: add raycast OnMouseEnter && OnMouseExit and set specific layer …
  Assets/Code/Scripts/Core/BaseMouseEventsController.cs
  Assets/Code/Scripts/Grid/Cells/Cell.cs
  Assets/Code/Scripts/Utils/LayerUtils.cs
  Assets/Code/Scripts/Utils/LayerUtils.cs.meta
Labels: feature
