Repository Nostralys-Studio/FrostfallSaga, pull requests merged in 2024-06, with the labels that each got.

#17 feat(path-finding): neighbors take height into account + unit tests added
  Assets/Code/Scripts/HexGrid/Cells/Cell.cs
  Assets/Code/Scripts/HexGrid/Cells/CellsNeighbors.cs
  Assets/Code/Scripts/HexGrid/Cells/CellsNeighbors.cs.meta
  Assets/Code/Scripts/HexGrid/Cells/CellsPathFinding.cs
  Assets/Code/Scripts/HexGrid/Cells/CellsPathFinding.cs.meta
  Assets/Code/Scripts/HexGrid/Cells/ECellHeight.cs
  Assets/Code/Scripts/HexGrid/Cells/Editor/CellEditor.cs
  Assets/Code/Scripts/HexGrid/HexGridGenerator.cs
  Assets/Code/Tests/EditModeTests/HexGrid/Cells.meta
  Assets/Code/Tests/EditModeTests/HexGrid/Cells/GetNeighborsTests.cs
  Assets/Code/Tests/EditModeTests/HexGrid/Cells/GetNeighborsTests.cs.meta
  Assets/Code/Tests/EditModeTests/HexGrid/Cells/GetShorterPathTests.cs
  Assets/Code/Tests/EditModeTests/HexGrid/Cells/GetShorterPathTests.cs.meta
  Assets/Code/Tests/EditModeTests/HexGrid/GridTestsHelper.cs
  Assets/Code/Tests/EditModeTests/HexGrid/GridTestsHelper.cs.meta
Labels: feature, tests

#20 Feat/ffs 104 active ability
  Assets/Art/UI/fireSpell.png
  Assets/Art/UI/fireSpell.png.meta
  Assets/Code/Scripts/Core/MouseController.cs
  Assets/Code/Scripts/Core/MouseEventsController.cs
  Assets/Code/Scripts/Core/MouseEventsController.cs.meta
  Assets/Code/Scripts/Fight/Ability.meta
  Assets/Code/Scripts/Fight/Ability/AbilityMouseEventsController.cs
  Assets/Code/Scripts/Fight/Ability/AbilityMouseEventsController.cs.meta
  Assets/Code/Scripts/Fight/Ability/ActiveAbilityScriptableObject.cs
  Assets/Code/Scripts/Fight/Ability/ActiveAbilityScriptableObject.cs.meta
  Assets/Code/Scripts/Fight/Ability/BaseAbility.cs
  Assets/Code/Scripts/Fight/Ability/BaseAbility.cs.meta
  Assets/Code/Scripts/Fight/Ability/BaseAbilityScriptableObject.cs
  Assets/Code/Scripts/Fight/Ability/BaseAbilityScriptableObject.cs.meta
  Assets/Code/Scripts/Fight/Effects/AEffect.cs
  Assets/Code/Scripts/Fight/Effects/DamageEffect.cs
  Assets/Code/Scripts/Fight/Effects/HealEffect.cs
  Assets/Code/Scripts/Fight/FrostfallSaga.Fight.asmdef
  Assets/Code/Scripts/Fight/Targeter/TargeterScriptableObject.cs
  Assets/Code/Scripts/Fight/Targeter/TargeterScriptableObject.cs.meta
  Assets/Code/Scripts/HexGrid/Cells/CellMouseEventsController.cs
  Assets/Code/Scripts/Kingdom/FrostfallSaga.Kingdom.asmdef
  Assets/Code/Scripts/Kingdom/KingdomManager.cs
  Assets/Level/Prefabs/Ability.prefab
  Assets/Level/Prefabs/Ability.prefab.meta
  Assets/Level/Scenes/KingdomScene.unity
  Assets/Level/ScriptableObjects/Fight.meta
  Assets/Level/ScriptableObjects/Fight/Abilities.meta
  Assets/Level/ScriptableObjects/Fight/Abilities/ExampleFireSpell.asset
  Assets/Level/ScriptableObjects/Fight/Abilities/ExampleFireSpell.asset.meta
  Assets/Level/ScriptableObjects/Fight/Effects.meta
  Assets/Level/ScriptableObjects/Fight/Effects/HighDamageEffect.asset
  Assets/Level/ScriptableObjects/Fight/Effects/HighDamageEffect.asset.meta
  Assets/Level/ScriptableObjects/Fight/Effects/LowHealEffect.asset
  Assets/Level/ScriptableObjects/Fight/Effects/LowHealEffect.asset.meta
  Assets/Level/ScriptableObjects/Fight/Targeters.meta
  Assets/Level/ScriptableObjects/Fight/Targeters/LargeRangeTargeter.asset
  Assets/Level/ScriptableObjects/Fight/Targeters/LargeRangeTargeter.asset.meta
  Assets/Level/ScriptableObjects/Fight/Targeters/MeleeTargeter.asset
  Assets/Level/ScriptableObjects/Fight/Targeters/MeleeTargeter.asset.meta
Labels: feature

#21 feat: separated physical and magical damage effects
  Assets/Code/Scripts/Fight/Effects/EMagicalElement.cs
  Assets/Code/Scripts/Fight/Effects/EMagicalElement.cs.meta
  Assets/Code/Scripts/Fight/Effects/MagicalDamageEffect.cs
  Assets/Code/Scripts/Fight/Effects/MagicalDamageEffect.cs.meta
  Assets/Code/Scripts/Fight/Effects/PhysicalDamageEffect.cs
  Assets/Code/Scripts/Fight/Effects/PhysicalDamageEffect.cs.meta
  Assets/Level/ScriptableObjects/Fight/Abilities/ExampleFireSpell.asset
  Assets/Level/ScriptableObjects/Fight/Effects/HighPhysicalDamageEffect.asset
  Assets/Level/ScriptableObjects/Fight/Effects/HighPhysicalDamageEffect.asset.meta
  Assets/Level/ScriptableObjects/Fight/Effects/MediumFireMagicalDamageEffect.asset
  Assets/Level/ScriptableObjects/Fight/Effects/MediumFireMagicalDamageEffect.asset.meta
Labels: feature

#22 feat(fighter): added effects for direct attack
  Assets/Code/Scripts/Fight/Ability/BaseAbilityScriptableObject.cs
  Assets/Code/Scripts/Fight/Effects/AEffectScriptableObject.cs
  Assets/Code/Scripts/Fight/Effects/AEffectScriptableObject.cs.meta
  Assets/Code/Scripts/Fight/Effects/HealEffectScriptableObject.cs
  Assets/Code/Scripts/Fight/Effects/HealEffectScriptableObject.cs.meta
  Assets/Code/Scripts/Fight/Effects/MagicalDamageEffectScriptableObject.cs
  Assets/Code/Scripts/Fight/Effects/MagicalDamageEffectScriptableObject.cs.meta
  Assets/Code/Scripts/Fight/Effects/PhysicalDamageEffectScriptableObject.cs
  Assets/Code/Scripts/Fight/Effects/PhysicalDamageEffectScriptableObject.cs.meta
  Assets/Code/Scripts/Fight/Fighter/FighterConfigurationScriptableObject.cs
  Assets/Level/ScriptableObjects/Fight/Fighters.meta
  Assets/Level/ScriptableObjects/Fight/Fighters/SkeletonExample.asset
  Assets/Level/ScriptableObjects/Fight/Fighters/SkeletonExample.asset.meta
Labels: feature

#23 refactor: renamed scriptable object classes to SO instead
  Assets/Code/Scripts/Fight/Ability/ActiveAbilitySO.cs
  Assets/Code/Scripts/Fight/Ability/ActiveAbilitySO.cs.meta
  Assets/Code/Scripts/Fight/Ability/BaseAbility.cs
  Assets/Code/Scripts/Fight/Ability/BaseAbilitySO.cs
  Assets/Code/Scripts/Fight/Ability/BaseAbilitySO.cs.meta
  Assets/Code/Scripts/Fight/Effects/AEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/AEffectSO.cs.meta
  Assets/Code/Scripts/Fight/Effects/HealEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/HealEffectSO.cs.meta
  Assets/Code/Scripts/Fight/Effects/MagicalDamageEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/MagicalDamageEffectSO.cs.meta
  Assets/Code/Scripts/Fight/Effects/PhysicalDamageEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/PhysicalDamageEffectSO.cs.meta
  Assets/Code/Scripts/Fight/Fighter/ActiveAbilitiesToAnimation.cs
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/Fighter/FighterConfigurationSO.cs
  Assets/Code/Scripts/Fight/Fighter/FighterConfigurationSO.cs.meta
  Assets/Code/Scripts/Fight/Targeter/TargeterSO.cs
  Assets/Code/Scripts/Fight/Targeter/TargeterSO.cs.meta
Labels: refactoring

#25 refactor(entities): isolated entities visual instead of putting it in…
  Assets/Code/Scripts/Entities/EntityConfigurationSO.cs
  Assets/Code/Scripts/Entities/EntityConfigurationSO.cs.meta
  Assets/Code/Scripts/EntitiesVisual.meta
  Assets/Code/Scripts/EntitiesVisual/EntityAnimationController.cs
  Assets/Code/Scripts/EntitiesVisual/EntityAnimationController.cs.meta
  Assets/Code/Scripts/EntitiesVisual/FrostfallSaga.EntitiesVisual.asmdef
  Assets/Code/Scripts/EntitiesVisual/FrostfallSaga.EntitiesVisual.asmdef.meta
  Assets/ScriptableObjects/Entities.meta
  Assets/ScriptableObjects/Entities/HeavyWarriorEntityConfiguration.asset
  Assets/ScriptableObjects/Entities/HeavyWarriorEntityConfiguration.asset.meta
Labels: refactoring

#27 feat(entites-groups): added entities group and updated kingdom manage…
  Assets/Art/Materials/M_Default_Red_Highlight.mat
  Assets/Art/Materials/M_Default_Red_Highlight.mat.meta
  Assets/Code/Scripts/Core/MouseEventsController.cs
  Assets/Code/Scripts/EntitiesVisual/EntityAnimationController.cs
  Assets/Code/Scripts/HexGrid/Cells/Cell.cs
  Assets/Code/Scripts/Kingdom/Entities/Entity.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups.meta
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EnemiesGroup.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EnemiesGroup.cs.meta
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EnemyEntitiesList.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EnemyEntitiesList.cs.meta
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntityGroup.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntityGroup.cs.meta
  Assets/Code/Scripts/Kingdom/KingdomManager.cs
  Assets/Level/Scenes/KingdomScene.unity
Labels: feature

#29 feat: cell fight behavior
  Assets/Code/Scripts/Fight/CellFightBehavior.meta
  Assets/Code/Scripts/Fight/CellFightBehavior/CellFightBehavior.cs
  Assets/Code/Scripts/Fight/CellFightBehavior/CellFightBehavior.cs.meta
  Assets/PolygonParticleFX.meta
  Assets/PolygonVikings.meta
Labels: feature

#30 feat: persisted fighter conf added + prefabs for hero and its bro
  Assets/Code/Scripts/Fight/Fighter/FighterConfigurationSO.cs
  Assets/Code/Scripts/Fight/Fighter/PersistedFighterConfigurationSO.cs
  Assets/Code/Scripts/Fight/Fighter/PersistedFighterConfigurationSO.cs.meta
  Assets/Code/Scripts/HexGrid/Editor/HexGridEditor.cs
  Assets/Code/Scripts/HexGrid/HexGrid.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EnemiesGroup.cs
  Assets/Level/Prefabs/Entities/Entity.prefab
  Assets/Level/Prefabs/Entities/HeavyWarriorEntityExample.prefab
  Assets/Level/Prefabs/Entities/Persisted.meta
  Assets/Level/Prefabs/Entities/Persisted/HeroEntity Variant.prefab
  Assets/Level/Prefabs/Entities/Persisted/HeroEntity Variant.prefab.meta
  Assets/Level/Prefabs/Entities/Persisted/JomsvikingEntity1 Variant.prefab
  Assets/Level/Prefabs/Entities/Persisted/JomsvikingEntity1 Variant.prefab.meta
  Assets/Level/Prefabs/Entities/Persisted/JomsvikingEntity2 Variant.prefab
  Assets/Level/Prefabs/Entities/Persisted/JomsvikingEntity2 Variant.prefab.meta
  Assets/Level/Scenes/KingdomScene.unity
  Assets/ScriptableObjects/Entities/Persisted.meta
  Assets/ScriptableObjects/Entities/Persisted/HeroEntityConfiguration.asset
  Assets/ScriptableObjects/Entities/Persisted/HeroEntityConfiguration.asset.meta
  Assets/ScriptableObjects/Entities/Persisted/JomsvikingEntityConfiguration1.asset
  Assets/ScriptableObjects/Entities/Persisted/JomsvikingEntityConfiguration1.asset.meta
  Assets/ScriptableObjects/Entities/Persisted/JomsvikingEntityConfiguration2.asset
  Assets/ScriptableObjects/Entities/Persisted/JomsvikingEntityConfiguration2.asset.meta
  Assets/ScriptableObjects/Fight/Fighters/Persisted.meta
  Assets/ScriptableObjects/Fight/Fighters/Persisted/PersistedHeroFighter.asset
  Assets/ScriptableObjects/Fight/Fighters/Persisted/PersistedHeroFighter.asset.meta
  Assets/ScriptableObjects/Fight/Fighters/Persisted/PersistedJomsviking2.asset
  Assets/ScriptableObjects/Fight/Fighters/Persisted/PersistedJomsviking2.asset.meta
  Assets/ScriptableObjects/Fight/Fighters/Persisted/PersistedJomsvikingFighter2.asset
  Assets/ScriptableObjects/Fight/Fighters/Persisted/PersistedJomsvikingFighter2.asset.meta
Labels: feature

#31 refactor(CellFightBehavior): renamed behavior to behaviour + IsFighte…
  Assets/Code/Scripts/Fight/CellFightBehavior/CellFightBehavior.cs
  Assets/Code/Scripts/Fight/CellFightBehaviour.meta
  Assets/Code/Scripts/Fight/CellFightBehaviour/CellFightBehaviour.cs
  Assets/Code/Scripts/Fight/CellFightBehaviour/CellFightBehaviour.cs.meta
Labels: refactoring

#33 Feat/ffs 132 entities encounter
  Assets/Art/Animations/BaseHeavy/BaseHeavyAnimator.controller
  Assets/Art/Animations/BaseHeavy/BaseHeavyReadyToFight.fbx
  Assets/Art/Animations/BaseHeavy/BaseHeavyReadyToFight.fbx.meta
  Assets/Code/Scripts/Core/SceneManager.cs
  Assets/Code/Scripts/Core/SceneTransitioner.cs
  Assets/Code/Scripts/Core/SceneTransitioner.cs.meta
  Assets/Code/Scripts/Kingdom/KingdomManager.cs
  Assets/Code/Scripts/Kingdom/KingdomToFightTransitioner.cs
  Assets/Code/Scripts/Kingdom/KingdomToFightTransitioner.cs.meta
  Assets/Level/Prefabs/Grid/HexGrid.prefab
  Assets/Level/Scenes/DevHub.unity
  Assets/Level/Scenes/FightScene.unity
  Assets/Level/Scenes/KingdomScene.unity
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  ProjectSettings/TagManager.asset
Labels: feature

#28 feat(FFS-74) Implement ApplyEffects
  Assets/Code/Scripts/Fight/Effects/AEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/EMagicalElement.cs
  Assets/Code/Scripts/Fight/Effects/HealEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/MagicalDamageEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/PhysicalDamageEffectSO.cs
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/Fighter/FighterConfigurationSO.cs
  Assets/Code/Scripts/Fight/Fighter/FighterStats.cs
  Packages/manifest.json
  Packages/packages-lock.json
Labels: feature

#35 Ffs 77 implement fighter move()
  Assets/Art/Animations/BaseHeavy/BaseHeavyAnimator.controller
  Assets/Art/Animations/BaseHeavy/BaseHeavyRun.fbx.meta
  Assets/Code/Scripts/EntitiesVisual/EntityVisualAnimationController.cs
  Assets/Code/Scripts/EntitiesVisual/EntityVisualAnimationController.cs.meta
  Assets/Code/Scripts/EntitiesVisual/EntityVisualMovementController.cs
  Assets/Code/Scripts/EntitiesVisual/EntityVisualMovementController.cs.meta
  Assets/Code/Scripts/EntitiesVisual/FrostfallSaga.EntitiesVisual.asmdef
  Assets/Code/Scripts/HexGrid/Cells/Cell.cs
  Assets/Code/Scripts/HexGrid/Cells/CellsPathFinding.cs
  Assets/Code/Scripts/Kingdom/Entities/Entity.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntitiesGroup.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroupsMovementController.cs
  Assets/Code/Scripts/Kingdom/KingdomManager.cs
  Assets/Code/Scripts/Kingdom/KingdomToFightTransitioner.cs
  Assets/Code/Scripts/Kingdom/MovePath.cs
  Assets/Code/Scripts/Kingdom/MovePath.cs.meta
  Assets/Code/Tests/EditModeTests/HexGrid/Cells/GetShorterPathTests.cs
  Assets/Code/Tests/EditModeTests/Kingdom/EntitiesGroupsMovementControllerTests.cs
  Assets/Level/Prefabs/Entities/Entity.prefab
  Assets/Level/Prefabs/EntitiesGroups/EnemiesGroupExample.prefab
  Assets/Level/Prefabs/EntitiesGroups/HeroGroup.prefab
  Assets/Level/Prefabs/EntitiesVisuals/EntityVisual.prefab
  Assets/Level/Scenes/KingdomScene.unity
Labels: feature

#36 feat: fight scene set up with default fighters and fight grid
  .vscode/settings.json
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Level/Prefabs/Fighters/Fighter.prefab
  Assets/Level/Prefabs/Grid/FightCell.prefab
  Assets/Level/Prefabs/Grid/FightCell.prefab.meta
  Assets/Level/Scenes/FightScene.unity
  Assets/ScriptableObjects/Fight/Fighters/Persisted/PersistedJomsvikingFighter1.asset
  Assets/ScriptableObjects/Fight/Fighters/Persisted/PersistedJomsvikingFighter1.asset.meta
Labels: feature

#37 feat(Fighter): implemented movement in fighter
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/FrostfallSaga.Fight.asmdef
  Assets/Code/Scripts/HexGrid/MovePath.cs
  Assets/Code/Scripts/HexGrid/MovePath.cs.meta
  Assets/Level/Scenes/FightScene.unity
Labels: feature

#40 feat(AFighterController): created abtract fighter controller class
  Assets/Code/Scripts/Fight/Controllers.meta
  Assets/Code/Scripts/Fight/Controllers/AFighterController.cs
  Assets/Code/Scripts/Fight/Controllers/AFighterController.cs.meta
Labels: feature
