Repository Nostralys-Studio/FrostfallSaga, pull requests merged in 2024-09, with the labels that each got.

#71 refactor: some renaming and lil bugs fixed
  Assets/Code/Scripts/Fight/Controllers/PlayerController.cs
  Assets/Code/Scripts/Fight/Controllers/RandomController.cs
  Assets/Code/Scripts/Fight/FightManager.cs
  Assets/Code/Scripts/Kingdom/Entities/EEntityID.cs
  Assets/Code/Scripts/Kingdom/Entities/EntityBuilder.cs
  Assets/Code/Scripts/Kingdom/Entities/EntityConfigurationSO.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EnemyEntitiesListSO.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntitiesGroup.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntitiesGroupBuilder.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntitiesListSO.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntitiesListSO.cs.meta
  Assets/Code/Scripts/Kingdom/EntitiesGroupsManager.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroupsSpawner.meta
  Assets/Code/Scripts/Kingdom/EntitiesGroupsSpawner/EntitiesGroupsSpawner.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroupsSpawner/EntitiesGroupsSpawner.cs.meta
  Assets/Code/Scripts/Kingdom/EntitiesGroupsSpawner/ImpossibleSpawnException.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroupsSpawner/ImpossibleSpawnException.cs.meta
  Assets/Code/Scripts/Kingdom/KingdomToFightTransitioner.cs
  Assets/Code/Scripts/KingdomToFight/EntityToFighter.cs
  Assets/Code/Scripts/KingdomToFight/FightToKingdomTransitioner.cs
  Assets/Code/Scripts/KingdomToFight/FightersSetupGenerator.cs
  Assets/Level/Scenes/KingdomScene.unity
  Assets/Resources/ScriptableObjects/Entities/JOMSVIKING1.asset
  Assets/Resources/ScriptableObjects/Entities/JOMSVIKING2.asset
  Assets/Resources/ScriptableObjects/Entities/SKELETON.asset
  Assets/Resources/ScriptableObjects/EntityToFighterDB.asset
  Assets/Resources/ScriptableObjects/Fight/Fighters/Persisted/PersistedHeroFighter.asset
  Assets/Resources/ScriptableObjects/Fight/Fighters/Persisted/PersistedJomsvikingFighter1.asset
  Assets/Resources/ScriptableObjects/Fight/Fighters/Persisted/PersistedJomsvikingFighter2.asset
  Assets/Resources/ScriptableObjects/Kingdom/AllEnemyEntities.asset
Labels: bug, refactoring

#72 feat(fight-scene): can launch fight scene without preFightData being …
  Assets/Code/Scripts/Fight/Fighter/FighterStats.cs
  Assets/Code/Scripts/Fight/FighterSetup.cs
  Assets/Code/Scripts/Fight/FightersGenerator.cs
  Assets/Code/Scripts/KingdomToFight/FightToKingdomTransitioner.cs
  Assets/Level/Scenes/FightScene.unity
Labels: devtool

#73 fix(FightManager): check for fight end when a fighter die
  Assets/Code/Scripts/Fight/FightManager.cs
Labels: bug

#74 Fighter action menu script
  Assets/Art/UI/UiPackWinScene.meta
  Assets/Art/UI/UiPackWinScene/Coin.png
  Assets/Art/UI/UiPackWinScene/Coin.png.meta
  Assets/Art/UI/UiPackWinScene/ItemBackground.png
  Assets/Art/UI/UiPackWinScene/ItemBackground.png.meta
  Assets/Art/UI/UiPackWinScene/ItemStackNb.png
  Assets/Art/UI/UiPackWinScene/ItemStackNb.png.meta
  Assets/Art/UI/UiPackWinScene/PannelMain.png
  Assets/Art/UI/UiPackWinScene/PannelMain.png.meta
  Assets/Art/UI/UiPackWinScene/Separation.png
  Assets/Art/UI/UiPackWinScene/Separation.png.meta
  Assets/Art/UI/UiPackWinScene/StarButton.png
  Assets/Art/UI/UiPackWinScene/StarButton.png.meta
  Assets/Art/UI/UiPackWinScene/tiretWin.png
  Assets/Art/UI/UiPackWinScene/tiretWin.png.meta
  Assets/Code/Scripts/Fight/FightToKingdomTransitioner.cs
  Assets/Code/Scripts/Fight/FightToKingdomTransitioner.cs.meta
  Assets/Code/Scripts/Fight/FightersGenerator.cs
  Assets/Code/Scripts/Fight/UI/FightEndMenuController.cs
  Assets/Code/Scripts/Fight/UI/FightEndMenuController.cs.meta
  Assets/Code/Scripts/KingdomToFight/PostFightDataGenerator.cs
  Assets/Code/Scripts/KingdomToFight/PostFightDataGenerator.cs.meta
  Assets/Level/Scenes/FightScene.unity
  Assets/Level/UI/EndFightScenePanel.uss
  Assets/Level/UI/EndFightScenePanel.uss.meta
  Assets/Level/UI/EndFightScenePanel.uxml
  Assets/Level/UI/EndFightScenePanel.uxml.meta
Labels: feature

#77 feat(CameraController): player can zoom in and out
  Assets/Code/Scripts/Core/CameraController.cs
  Assets/Code/Scripts/Core/CameraController.cs.meta
  Assets/Code/Scripts/Core/FrostfallSaga.Core.asmdef
  Assets/Code/Scripts/Fight/FightCamera.cs
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntitiesGroup.cs
  Assets/Code/Scripts/Kingdom/KingdomLoader.cs
  Assets/Level/Prefabs/EntitiesGroups/HeroGroup.prefab
  Assets/Level/Prefabs/Fighters/Fighter.prefab
  Assets/Level/Scenes/FightScene.unity
  Assets/Level/Scenes/KingdomScene.unity
Labels: feature

#78 feat: add some biomes and terrains
  Assets/Code/Scripts/Grid/Cells/BiomeTypeSO.cs
  Assets/Code/Scripts/Grid/Cells/BiomeTypeSO.cs.meta
  Assets/Resources/ScriptableObjects/Grid/Biome.meta
  Assets/Resources/ScriptableObjects/Grid/Biome/BiomeTypeDarkForest.asset
  Assets/Resources/ScriptableObjects/Grid/Biome/BiomeTypeDarkForest.asset.meta
  Assets/Resources/ScriptableObjects/Grid/Biome/BiomeTypeSnow.asset
  Assets/Resources/ScriptableObjects/Grid/Biome/BiomeTypeSnow.asset.meta
  Assets/Resources/ScriptableObjects/Grid/Biome/BiomeTypeTundra.asset
  Assets/Resources/ScriptableObjects/Grid/Biome/BiomeTypeTundra.asset.meta
  Assets/Resources/ScriptableObjects/Grid/Biome/BiomeTypeValley.asset
  Assets/Resources/ScriptableObjects/Grid/Biome/BiomeTypeValley.asset.meta
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeDarkForest.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeDarkForest.asset.meta
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeFrozenWater.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeFrozenWater.asset.meta
Labels: feature

#80 feat(CameraController): added translation on camera
  Assets/Art/Materials/PolyVikings_Character_Mat_Black.mat
  Assets/Art/Materials/PolyVikings_Character_Mat_Black.mat.meta
  Assets/Art/Materials/PolyVikings_Character_Mat_Brown.mat
  Assets/Art/Materials/PolyVikings_Character_Mat_Brown.mat.meta
  Assets/Art/Models/Characters.fbx.meta
  Assets/Art/Textures/Characters_Black.png.meta
  Assets/Art/Textures/Characters_Brown.png.meta
  Assets/Code/Scripts/Core/CameraController.cs
  Assets/FFS.unity
  Assets/FFS.unity.meta
  Assets/Level/Scenes/FightScene.unity
Labels: feature

#81 feat(CameraController): fully updated to follow a virtual target instead
  Assets/Code/Scripts/Core/CameraController.cs
  Assets/Level/Scenes/FightScene.unity
  Assets/Level/Scenes/KingdomScene.unity
Labels: feature

#79 feat: add a link into hex generator
  Assets/Code/Scripts/Grid/Cells/Cell.cs
  Assets/Code/Scripts/Grid/HexGridGenerator.cs
  Assets/Code/Tests/EditModeTests/CommonTestsHelper.cs
  Assets/Code/Tests/EditModeTests/HexGrid/Cells/GetNeighborsTests.cs
  Assets/Code/Tests/EditModeTests/HexGrid/Cells/GetShorterPathTests.cs
  Assets/Level/Scenes/KingdomScene.unity
  Assets/Resources/ScriptableObjects/Grid/Biome/BiomeTypeDarkForest.asset
  Assets/Resources/ScriptableObjects/Grid/Biome/BiomeTypeSnow.asset
  Assets/Resources/ScriptableObjects/Grid/Biome/BiomeTypeTundra.asset
  Assets/Resources/ScriptableObjects/Grid/Biome/BiomeTypeValley.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeDarkForest.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeForest.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeFrozenWater.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeMountain.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypePlain.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeWater.asset
Labels: feature

#84 Ffs 233 add visuals to cell
  Assets/Art/Materials/CellMaterials.meta
  Assets/Art/Materials/CellMaterials/M_DarkForest.mat
  Assets/Art/Materials/CellMaterials/M_DarkForest.mat.meta
  Assets/Art/Materials/CellMaterials/M_Forest.mat
  Assets/Art/Materials/CellMaterials/M_Forest.mat.meta
  Assets/Art/Materials/CellMaterials/M_FrozenWater.mat
  Assets/Art/Materials/CellMaterials/M_FrozenWater.mat.meta
  Assets/Art/Materials/CellMaterials/M_Mountain.mat
  Assets/Art/Materials/CellMaterials/M_Mountain.mat.meta
  Assets/Art/Materials/CellMaterials/M_Plain.mat
  Assets/Art/Materials/CellMaterials/M_Plain.mat.meta
  Assets/Art/Materials/CellMaterials/M_Water.mat
  Assets/Art/Materials/CellMaterials/M_Water.mat.meta
  Assets/Code/Scripts/Grid/Cells/Cell.cs
  Assets/Code/Scripts/Grid/Cells/TerrainTypeSO.cs
  Assets/Code/Scripts/Grid/HexGridGenerator.cs
Labels: feature

#83 fix(UI): ui layer blocks mouse interations
  Assets/Code/Scripts/Core/BaseMouseEventsController.cs
  Assets/Code/Scripts/Core/BaseUIController.cs
  Assets/Code/Scripts/Core/BaseUIController.cs.meta
  Assets/Code/Scripts/Core/CameraController.cs
  Assets/Code/Scripts/Fight/UI/FightEndMenuController.cs
  Assets/Code/Scripts/Fight/UI/FighterActionPanelController.cs
  Assets/Code/Scripts/Fight/UI/FightersOrderTimelineController.cs
  Assets/Level/Scenes/FightScene.unity
Labels: bug

#82 Feat/ffs 188 mouse detection on entities
  Assets/Code/Scripts/Core/BaseMouseEventsController.cs
  Assets/Code/Scripts/Fight/Controllers/PlayerController.cs
  Assets/Code/Scripts/Fight/Fighter/EntityMouseEventsController.cs
  Assets/Code/Scripts/Fight/Fighter/EntityMouseEventsController.cs.meta
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntitiesGroup.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroupsManager.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroupsMovementController.cs
  Assets/Level/Prefabs/Fighters/Fighter.prefab
  Assets/Level/Scenes/KingdomScene.unity
Labels: feature

#88 fix: grid map for the kingdom
  Assets/Level/Scenes/KingdomScene.unity
Labels: bug

#92 fix: visual responsive
  Assets/Level/UI/EndFightScenePanel.uxml
  Assets/Level/UI/FightScenePanel.uss
  Assets/Level/UI/FightScenePanel.uxml
Labels: bug

#93 feat(AI/Node): created node class for incoming AI controller
  Assets/Code/Scripts/Fight/Controllers/AI.meta
  Assets/Code/Scripts/Fight/Controllers/AI/Node.cs
  Assets/Code/Scripts/Fight/Controllers/AI/Node.cs.meta
Labels: feature
