Repository Nostralys-Studio/FrostfallSaga, pull requests merged in 2024-11, with the labels that each got.

#125 Feat/ffs 215 behaviour tree controller
  Assets/Code/Scripts/BehaviourTree/BTree.cs
  Assets/Code/Scripts/BehaviourTree/Node.cs
  Assets/Code/Scripts/Fight/Ability/BaseAbilitySO.cs
  Assets/Code/Scripts/Fight/Controllers/FBTController.cs
  Assets/Code/Scripts/Fight/Controllers/FBTController.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/DamageTargetAction.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/DamageTargetAction.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/EndTurnAction.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/EndTurnAction.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/MoveToClosestTargetAction.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/MoveToClosestTargetAction.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Checks.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Checks/CanDamageTargetCheck.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Checks/CanDamageTargetCheck.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Checks/CanMoveCheck.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Checks/CanMoveCheck.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/EDamagePreference.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/EDamagePreference.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/EFighterBehaviourTreeID.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/EFighterBehaviourTreeID.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/ETargetType.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/ETargetType.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/FBTNode.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/FBTNode.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/FighterBehaviourTree.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/FighterBehaviourTree.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/FighterBehaviourTreeFactory.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/FighterBehaviourTreeFactory.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/MalformedFBTException.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/MalformedFBTException.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Trees.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Trees/AggressiveFBT.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Trees/AggressiveFBT.cs.meta
  Assets/Code/Scripts/Fight/Controllers/PlayerController.cs
  Assets/Code/Scripts/Fight/Controllers/RandomController.cs
  Assets/Code/Scripts/Fight/Effects/AEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/ApplyStatusEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/HealEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/MagicalDamageEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/PhysicalDamageEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/RemoveStatusEffectSO.cs
  Assets/Code/Scripts/Fight/FightManager.cs
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/Fighter/PersonalityTraitSO.cs
  Assets/Code/Scripts/Fight/Fighter/PersonalityTraitSO.cs.meta
  Assets/Code/Scripts/Fight/FighterSetup.cs
  Assets/Code/Scripts/Fight/FightersGenerator.cs
  Assets/Code/Scripts/Fight/UI/FighterActionPanelController.cs
  Assets/Code/Scripts/KingdomToFight/FighterConfigurationSO.cs
  Assets/Code/Scripts/KingdomToFight/FightersSetupGenerator.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FightTestsHelper.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterUseActiveAbilityTests.cs
  Assets/Level/Scenes/FightScene.unity
  Assets/Resources/ScriptableObjects/Fight/Effects/MediumFireMagicalDamageEffect.asset
  Assets/Resources/ScriptableObjects/Fight/Fighters/PersonalityTraits.meta
  Assets/Resources/ScriptableObjects/Fight/Fighters/PersonalityTraits/AggressivePT.asset
  Assets/Resources/ScriptableObjects/Fight/Fighters/PersonalityTraits/AggressivePT.asset.meta
  Assets/Resources/ScriptableObjects/Fight/Targeters/LargeRangeTargeter.asset
Labels: bug, feature

#126 refactor: cellFightBehaviour turned into FightCell class inheriting f…
  Assets/Code/Scripts/Fight/CellFightBehaviour/CellFightBehaviour.cs
  Assets/Code/Scripts/Fight/CellFightBehaviour/FightCellNeighbors.cs
  Assets/Code/Scripts/Fight/CellFightBehaviour/FightCellNeighbors.cs.meta
  Assets/Code/Scripts/Fight/CellFightBehaviour/FightCellsPathFinding.cs
  Assets/Code/Scripts/Fight/CellFightBehaviour/FightCellsPathFinding.cs.meta
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/DamageTargetAction.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/MoveToClosestTargetAction.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Checks/CanDamageTargetCheck.cs
  Assets/Code/Scripts/Fight/Controllers/PlayerController.cs
  Assets/Code/Scripts/Fight/Controllers/RandomController.cs
  Assets/Code/Scripts/Fight/FightCells.meta
  Assets/Code/Scripts/Fight/FightCells/FightCell.cs
  Assets/Code/Scripts/Fight/FightCells/FightCell.cs.meta
  Assets/Code/Scripts/Fight/FightCells/Impediments.meta
  Assets/Code/Scripts/Fight/FightManager.cs
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/Targeter/TargeterSO.cs
  Assets/Code/Scripts/Grid/Cells/Cell.cs
  Assets/Code/Scripts/Grid/CellsNeighbors.cs
  Assets/Code/Scripts/Grid/CellsPathFinding.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntitiesGroup.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroupsSpawner/EntitiesGroupsSpawner.cs
  Assets/Code/Tests/EditModeTests/CommonTestsHelper.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FightTestsHelper.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterUseActiveAbilityTests.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterUseDirectAttackTests.cs
  Assets/Code/Tests/EditModeTests/HexGrid/Cells/GetNeighborsTests.cs
  Assets/Code/Tests/EditModeTests/Kingdom/EntitiesGroupsMovementControllerTests.cs
  Assets/Level/Prefabs/Grid/FightCell.prefab
  Assets/Level/Scenes/FightScene.unity
  Assets/Resources/ScriptableObjects/Fight/Fighters/Ennemies/Hummanoid/SkeletonExample.asset
Labels: refactoring

#127 fix: check if already close to target before moving + avoid infinite …
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/DamageTargetAction.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/MoveToClosestTargetAction.cs
  Assets/Code/Scripts/Fight/FightCells/Impediments/AImpedimentSO.cs
  Assets/Code/Scripts/Fight/FightCells/Impediments/AImpedimentSO.cs.meta
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
Labels: bug

#128 feat(FightCells): impediments added
  Assets/Code/Scripts/Fight/Effects/AEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/ApplyStatusEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/HealEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/MagicalDamageEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/PhysicalDamageEffectSO.cs
  Assets/Code/Scripts/Fight/Effects/RemoveStatusEffectSO.cs
  Assets/Code/Scripts/Fight/FightCells/FightCell.cs
  Assets/Code/Scripts/Fight/FightCells/Impediments/AImpedimentSO.cs
  Assets/Code/Scripts/Fight/FightCells/Impediments/ETrapTriggerTime.cs
  Assets/Code/Scripts/Fight/FightCells/Impediments/ETrapTriggerTime.cs.meta
  Assets/Code/Scripts/Fight/FightCells/Impediments/ObstacleSO.cs
  Assets/Code/Scripts/Fight/FightCells/Impediments/ObstacleSO.cs.meta
  Assets/Code/Scripts/Fight/FightCells/Impediments/TrapSO.cs
  Assets/Code/Scripts/Fight/FightCells/Impediments/TrapSO.cs.meta
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Resources/ScriptableObjects/Fight/Impediments.meta
  Assets/Resources/ScriptableObjects/Fight/Impediments/Obstacles.meta
  Assets/Resources/ScriptableObjects/Fight/Impediments/Obstacles/ObstacleExample.asset
  Assets/Resources/ScriptableObjects/Fight/Impediments/Obstacles/ObstacleExample.asset.meta
  Assets/Resources/ScriptableObjects/Fight/Impediments/Traps.meta
  Assets/Resources/ScriptableObjects/Fight/Impediments/Traps/TrapExample.asset
  Assets/Resources/ScriptableObjects/Fight/Impediments/Traps/TrapExample.asset.meta
Labels: feature

#132 feat: god favors mechanic added to the game
  Assets/Code/Scripts/Fight/Abilities/ActiveAbilitySO.cs
  Assets/Code/Scripts/Fight/Abilities/PassiveAbilitySO.cs
  Assets/Code/Scripts/Fight/Controllers/PlayerController.cs
  Assets/Code/Scripts/Fight/Effects/AEffect.cs
  Assets/Code/Scripts/Fight/Effects/ApplyStatusesEffect.cs
  Assets/Code/Scripts/Fight/Effects/HealEffect.cs
  Assets/Code/Scripts/Fight/Effects/MagicalDamageEffect.cs
  Assets/Code/Scripts/Fight/Effects/PhysicalDamageEffect.cs
  Assets/Code/Scripts/Fight/Effects/RemoveStatusesEffect.cs
  Assets/Code/Scripts/Fight/Effects/UpdateMutableStatEffect.cs
  Assets/Code/Scripts/Fight/FightManager.cs
  Assets/Code/Scripts/Fight/Fighter/ClassGodSO.cs
  Assets/Code/Scripts/Fight/Fighter/ClassGodSO.cs.meta
  Assets/Code/Scripts/Fight/Fighter/EGodFavorsAction.cs
  Assets/Code/Scripts/Fight/Fighter/EGodFavorsAction.cs.meta
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/Fighter/FighterClassSO.cs
  Assets/Code/Scripts/Fight/Fighter/GodFavorsActionToInt.cs
  Assets/Code/Scripts/Fight/Fighter/GodFavorsActionToInt.cs.meta
  Assets/Code/Scripts/Fight/FighterConditions/EStatConditionType.cs
  Assets/Code/Scripts/Fight/Statuses/EStatusType.cs
  Assets/Resources/ScriptableObjects/Fight/Abilities/ActiveAbilities/ExampleTrapAdder.asset
  Assets/Resources/ScriptableObjects/Fight/Fighters/ClassSO/ClassGods.meta
  Assets/Resources/ScriptableObjects/Fight/Fighters/ClassSO/ClassGods/FreyjaClassGod.asset
  Assets/Resources/ScriptableObjects/Fight/Fighters/ClassSO/ClassGods/FreyjaClassGod.asset.meta
  Assets/Resources/ScriptableObjects/Fight/Fighters/ClassSO/ClassGods/TyrClassGod.asset
  Assets/Resources/ScriptableObjects/Fight/Fighters/ClassSO/ClassGods/TyrClassGod.asset.meta
  Assets/Resources/ScriptableObjects/Fight/Fighters/ClassSO/ThiefClass.asset
  Assets/Resources/ScriptableObjects/Fight/Fighters/ClassSO/WarriorClass.asset
  Assets/Resources/ScriptableObjects/Fight/Fighters/ClassSO/WizardClass.asset
Labels: feature

#133 Feat/ffs 291 effects on masterstrokes
  Assets/Code/Scripts/Fight/Abilities/ActiveAbilitySO.cs
  Assets/Code/Scripts/Fight/Abilities/BaseAbilitySO.cs
  Assets/Code/Scripts/Fight/Abilities/PassiveAbilitySO.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/DamageTargetAction.cs
  Assets/Code/Scripts/Fight/Controllers/PlayerController.cs
  Assets/Code/Scripts/Fight/Controllers/RandomController.cs
  Assets/Code/Scripts/Fight/Editor/AEffectDrawer.cs
  Assets/Code/Scripts/Fight/Editor/ActiveAbilitySOEditor.cs
  Assets/Code/Scripts/Fight/Effects/AEffect.cs
  Assets/Code/Scripts/Fight/Effects/ApplyStatusesEffect.cs
  Assets/Code/Scripts/Fight/Effects/HealEffect.cs
  Assets/Code/Scripts/Fight/Effects/MagicalDamageEffect.cs
  Assets/Code/Scripts/Fight/Effects/PhysicalDamageEffect.cs
  Assets/Code/Scripts/Fight/Effects/RemoveStatusesEffect.cs
  Assets/Code/Scripts/Fight/Effects/UpdateMutableStatEffect.cs
  Assets/Code/Scripts/Fight/FightCells/Impediments/TrapSO.cs
  Assets/Code/Scripts/Fight/Fighter/ActiveAbilityToAnimation.cs
  Assets/Code/Scripts/Fight/Fighter/ActiveAbilityToAnimation.cs.meta
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/FighterSetup.cs
  Assets/Code/Scripts/Fight/Statuses/BleedStatus.cs
  Assets/Code/Scripts/Fight/Statuses/ParalysisStatus.cs
  Assets/Code/Scripts/Fight/Statuses/SlownessStatus.cs
  Assets/Code/Scripts/Fight/Statuses/StatusesManager.cs
  Assets/Code/Scripts/Fight/Statuses/WeaknessStatus.cs
  Assets/Code/Scripts/Fight/UI/FighterActionPanelController.cs
  Assets/Code/Scripts/KingdomToFight/FighterConfigurationSO.cs
  Assets/Code/Scripts/KingdomToFight/FightersSetupGenerator.cs
  Assets/Code/Scripts/KingdomToFight/PersistedFighterConfigurationSO.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterStatusAbilitiesTests.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterUseActiveAbilityTests.cs
  Assets/Code/Tests/EditModeTests/Fight/Fighter/FighterUseDirectAttackTests.cs
  Assets/Level/Scenes/FightScene.unity
  Assets/Resources/EditModeTests/ScriptableObjects/TestClassGod.asset
  Assets/Resources/EditModeTests/ScriptableObjects/TestClassGod.asset.meta
  Assets/Resources/EditModeTests/ScriptableObjects/TestFighter.asset
  Assets/Resources/EditModeTests/ScriptableObjects/TestWarriorClass.asset
  Assets/Resources/ScriptableObjects/Fight/Abilities/ActiveAbilities/ExampleFireSpell.asset
  Assets/Resources/ScriptableObjects/Fight/Abilities/ActiveAbilities/ExampleHeightCellModifier.asset
  Assets/Resources/ScriptableObjects/Fight/Abilities/ActiveAbilities/ExampleObstacleAdder.asset
  Assets/Resources/ScriptableObjects/Fight/Abilities/ActiveAbilities/ExampleTrapAdder.asset
  Assets/Resources/ScriptableObjects/Fight/Abilities/ActiveAbilities/ExampleWeaknessAbility.asset
  Assets/Resources/ScriptableObjects/Fight/Abilities/ActiveAbilities/ExampleWeaknessRemoverAbility.asset
Labels: feature

#137 fix: duplicated usings removed
  Assets/Code/Scripts/Fight/Abilities/AbilityAnimation/Executors/AExternalAbilityAnimationExecutor.cs
  Assets/Code/Scripts/Fight/Abilities/AbilityAnimation/Executors/ReturnToOriginCellInternalExecutor.cs
  Assets/Code/Scripts/Fight/Abilities/AbilityAnimation/TestAbilityAnimationLauncher.cs
  Assets/Code/Scripts/Fight/Controllers/RandomController.cs
Labels: refactoring

#138 Improve UI Fight
  Assets/Art/UI/CharacterPanel/Darkness Icon.png
  Assets/Art/UI/CharacterPanel/Darkness Icon.png.meta
  Assets/Art/UI/CharacterPanel/Defense Icon.png
  Assets/Art/UI/CharacterPanel/Defense Icon.png.meta
  Assets/Art/UI/CharacterPanel/Dexterity Icon.png
  Assets/Art/UI/CharacterPanel/Dexterity Icon.png.meta
  Assets/Art/UI/CharacterPanel/DodgeChance Icon.png
  Assets/Art/UI/CharacterPanel/DodgeChance Icon.png.meta
  Assets/Art/UI/CharacterPanel/Earth Icon.png
  Assets/Art/UI/CharacterPanel/Earth Icon.png.meta
  Assets/Art/UI/CharacterPanel/Fire Icon.png
  Assets/Art/UI/CharacterPanel/Fire Icon.png.meta
  Assets/Art/UI/CharacterPanel/Ice Icon.png
  Assets/Art/UI/CharacterPanel/Ice Icon.png.meta
  Assets/Art/UI/CharacterPanel/Initiative Icon.png
  Assets/Art/UI/CharacterPanel/Initiative Icon.png.meta
  Assets/Art/UI/CharacterPanel/Light Icon.png
  Assets/Art/UI/CharacterPanel/Light Icon.png.meta
  Assets/Art/UI/CharacterPanel/Lightning Icon.png
  Assets/Art/UI/CharacterPanel/Lightning Icon.png.meta
  Assets/Art/UI/CharacterPanel/Luck Icon.png
  Assets/Art/UI/CharacterPanel/Luck Icon.png.meta
  Assets/Art/UI/CharacterPanel/Magic Icon.png
  Assets/Art/UI/CharacterPanel/Magic Icon.png.meta
  Assets/Art/UI/CharacterPanel/MasterStroke Icon.png
  Assets/Art/UI/CharacterPanel/MasterStroke Icon.png.meta
  Assets/Art/UI/CharacterPanel/PhysicalResistance Icon.png
  Assets/Art/UI/CharacterPanel/PhysicalResistance Icon.png.meta
  Assets/Art/UI/CharacterPanel/Strenght Icon.png
  Assets/Art/UI/CharacterPanel/Strenght Icon.png.meta
  Assets/Art/UI/CharacterPanel/Sword Icon.png
  Assets/Art/UI/CharacterPanel/Sword Icon.png.meta
  Assets/Art/UI/CharacterPanel/Tenacity Icon.png
  Assets/Art/UI/CharacterPanel/Tenacity Icon.png.meta
  Assets/Art/UI/fonts/Norse-KaWl.otf
  Assets/Art/UI/fonts/Norse-KaWl.otf.meta
  Assets/Art/UI/fonts/NorseBold-2Kge.otf
  Assets/Art/UI/fonts/NorseBold-2Kge.otf.meta
  Assets/Art/UI/fonts/elder-futhark.zip
  Assets/Art/UI/fonts/elder-futhark.zip.meta
  Assets/Code/Scripts/Fight/UI/FightUI
  Assets/Code/Scripts/Fight/UI/FightUI.meta
  Assets/Level/UI/FightCharacterPanel.uss
  Assets/Level/UI/FightCharacterPanel.uss.meta
  Assets/Level/UI/FightCharacterPanel.uxml
  Assets/Level/UI/FightCharacterPanel.uxml.meta
  Assets/Level/UI/FightDamage.uss
  Assets/Level/UI/FightDamage.uss.meta
  Assets/Level/UI/FightDamage.uxml
  Assets/Level/UI/FightDamage.uxml.meta
  Assets/Level/UI/FightScenePanel.uss
  Assets/Level/UI/FightScenePanel.uxml
  Assets/Level/UI/FightStatsFlottante.uss
  Assets/Level/UI/FightStatsFlottante.uss.meta
  Assets/Level/UI/FightStatsFlottante.uxml
  Assets/Level/UI/FightStatsFlottante.uxml.meta
Labels: feature

#140 feat(fight-ui):
  Assets/Code/Scripts/Fight/UI/FighterActionPanelController.cs
  Assets/Code/Scripts/Fight/UI/FightersOrderTimelineController.cs
  Assets/Code/Scripts/Fight/UI/TurnLabelController.cs
  Assets/Code/Scripts/Fight/UI/TurnLabelController.cs.meta
  Assets/Level/Scenes/FightScene.unity
  Assets/Level/UI/FightScenePanel.uxml
Labels: feature
