Repository Nostralys-Studio/FrostfallSaga, pull requests merged in 2025-01, with the labels that each got.

#167 refactor: renamed and indentation
  Assets/Code/Scripts/Grid/Cells/Cell.cs
  Assets/Code/Scripts/Grid/Editor/HexGridGeneratorEditor.cs
  Assets/Code/Scripts/Grid/HexGridGenerator.cs
Labels: refactoring

#172 Fix/ffs 379 floating bar position
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Level/Prefabs/Fighters/Fighter.prefab
  Assets/Level/Prefabs/Fighters/Fighter.prefab.meta
  Assets/Level/Prefabs/Fighters/SkeletonFighter.prefab
  Assets/Level/Scenes/FightScene.unity
Labels: bug, refactoring

#171 fix(FighterDetailsPanel): use visibility hidden to hide panel to not block mouse
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Level/Prefabs/Fighters/Fighter.prefab
  Assets/Level/Prefabs/Fighters/Fighter.prefab.meta
  Assets/Level/Prefabs/Fighters/SkeletonFighter.prefab
  Assets/Level/Scenes/FightScene.unity
  Assets/Level/UI/Fight/FighterDetailsPanel.uss
Labels: bug

#173 fix: effects feedback simplified + ability bar & colliders fixed
  Assets/Code/Scripts/Fight/Fighter/DirectAttackManager.cs
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/UI/EffectsFeedbackController.cs
  Assets/Code/Scripts/Fight/UI/FighterActionPanelController.cs
  Assets/Level/Prefabs/Abilities/PassiveAbilitiesAnimation/HealingAnimationExample.prefab
  Assets/Level/Prefabs/EntitiesVisuals/Warrior/Test warrior weapon/BaseAxe.prefab
  Assets/Level/Prefabs/EntitiesVisuals/Warrior/Warrior Variant Armed.prefab
  Assets/Level/Prefabs/Fighters/Fighter.prefab
  Assets/Level/Scenes/FightScene.unity
  Assets/Level/UI/Fight/EffectFeedback.uss
  Assets/Level/UI/Fight/EffectFeedback.uxml
  Assets/Resources/ScriptableObjects/Fight/Abilities/ActiveAbilities/ExampleIceBlast.asset
  Assets/Resources/ScriptableObjects/Items/ExampleWeapon.asset
Labels: bug, refactoring

#175 feat(Kingdom): new KingdomCell and occupiers added + city prefab
  Assets/Code/Scripts/EntitiesVisual/EntityVisualMovementController.cs
  Assets/Code/Scripts/Fight/FightCells/FightCell.cs
  Assets/Code/Scripts/Grid/Cells/Cell.cs
  Assets/Code/Scripts/Kingdom/Cities/City.cs
  Assets/Code/Scripts/Kingdom/Cities/City.cs.meta
  Assets/Code/Scripts/Kingdom/Cities/CityMouseEventsController.cs
  Assets/Code/Scripts/Kingdom/Cities/CityMouseEventsController.cs.meta
  Assets/Code/Scripts/Kingdom/Entities/Entity.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntitiesGroup.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroups/EntitiesGroupBuilder.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroupsManager.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroupsMovementController.cs
  Assets/Code/Scripts/Kingdom/EntitiesGroupsSpawner/EntitiesGroupsSpawner.cs
  Assets/Code/Scripts/Kingdom/KingdomCell.cs
  Assets/Code/Scripts/Kingdom/KingdomCell.cs.meta
  Assets/Code/Scripts/Kingdom/KingdomCellOccupier.cs
  Assets/Code/Scripts/Kingdom/KingdomCellOccupier.cs.meta
  Assets/Code/Scripts/Kingdom/KingdomLoader.cs
  Assets/Code/Scripts/Kingdom/KingdomToFightTransitioner.cs
  Assets/Code/Scripts/Kingdom/UI.meta
  Assets/Code/Scripts/Kingdom/UI/CityNamePanelsController.cs
  Assets/Code/Scripts/Kingdom/UI/CityNamePanelsController.cs.meta
  Assets/Code/Tests/EditModeTests/CommonTestsHelper.cs
  Assets/Code/Tests/EditModeTests/Kingdom/EntitiesGroupsMovementControllerTests.cs
  Assets/Code/Tests/EditModeTests/Kingdom/KingdomTestsHelper.cs
  Assets/Level/Prefabs/Cities.meta
  Assets/Level/Prefabs/Cities/BaseCity.prefab
  Assets/Level/Prefabs/Cities/BaseCity.prefab.meta
  Assets/Level/Prefabs/Cities/ExampleCity.prefab
  Assets/Level/Prefabs/Cities/ExampleCity.prefab.meta
  Assets/Level/Prefabs/Entities/Humanoids/SkeletonEntity.prefab
  Assets/Level/Prefabs/EntitiesVisuals/Warrior/Warrior Variant Armed.prefab
  Assets/Level/Prefabs/Grid/KingdomCell.prefab
  Assets/Level/Prefabs/Grid/KingdomCell.prefab.meta
  Assets/Level/Scenes/KingdomScene.unity
  Assets/Level/UI/FontAssets/MorrisRomanBlack SDF.asset
  Assets/Level/UI/Kingdom.meta
  Assets/Level/UI/Kingdom/CityNamePanel.uxml
  Assets/Level/UI/Kingdom/CityNamePanel.uxml.meta
  Assets/Level/UI/Kingdom/KingdomPanel.uxml
  Assets/Level/UI/Kingdom/KingdomPanel.uxml.meta
  Assets/Resources/ScriptableObjects/Kingdom/Cities/ExampleCityConfiguration.asset
  Assets/Resources/ScriptableObjects/Kingdom/Cities/ExampleCityConfiguration.asset.meta
  ProjectSettings/TagManager.asset
Labels: feature

#181 feat: add class to count and generate percentages of biomes and terra…
  Assets/Code/Scripts/Grid/CellAnalysis.cs
  Assets/Code/Scripts/Grid/CellAnalysis.cs.meta
  Assets/Code/Scripts/Grid/Cells/Cell.cs
  Assets/Code/Scripts/Grid/CellsNeighbors.cs
  Assets/Code/Scripts/Grid/EditorWindow.meta
  Assets/Code/Scripts/Grid/EditorWindow/CellAnalysisWindow.cs
  Assets/Code/Scripts/Grid/EditorWindow/CellAnalysisWindow.cs.meta
  Assets/Code/Scripts/Grid/HexGrid.cs
Labels: feature, REVIEW DONE
