Repository Nostralys-Studio/FrostfallSaga, pull requests merged in 2025-03, with the labels that each got.

#206 feat(quests): quests can be added through dialogue
  Assets/Code/Scripts/Core/Dialogues/DialogueLine.cs
  Assets/Code/Scripts/Core/Dialogues/DialogueUIProcessor.cs
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueNode.cs
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueSOEditor.cs
  Assets/Level/Scenes/CityScene.unity
  Assets/Level/Scenes/KingdomScene.unity
  Assets/Resources/ScriptableObjects/Quests/ExampleActionsQuest/ExampleActionsQuest2.asset
Labels: feature

#222 feat(HeroTeam): stycas can be added and withdrawn from hero team
  Assets/Code/Scripts/Core/HeroTeam/HeroTeam.cs
Labels: feature

#227 feat(invenotry-ui): coin displayed in inventory
  Assets/Code/Scripts/InventorySystem/UI/InventoryBagPanelUIController.cs
  Assets/Level/UI/Inventory/InventoryBagPanel.uxml
Labels: feature

#228 feat(HeroTeam): hero team data persisted in scriptable object
  Assets/Code/Scripts/Core/HeroTeam/Hero.cs
  Assets/Code/Scripts/Core/HeroTeam/HeroTeam.cs
  Assets/Code/Scripts/Core/HeroTeam/HeroTeamConfigurationSO.cs
  Assets/Code/Scripts/Core/HeroTeam/HeroTeamConfigurationSO.cs.meta
  Assets/Resources/ScriptableObjects/Entities/HeroTeamConfiguration.asset
  Assets/Resources/ScriptableObjects/Entities/HeroTeamConfiguration.asset.meta
Labels: feature

#225 feat(dungeon): reward added to dungeons
  Assets/Code/Scripts/Core/Dungeons/DungeonConfigurationSO.cs
  Assets/Code/Scripts/Core/HeroTeam/Hero.cs
  Assets/Code/Scripts/Core/HeroTeam/HeroTeam.cs
  Assets/Code/Scripts/Core/HeroTeam/HeroTeamConfigurationSO.cs
  Assets/Code/Scripts/Core/HeroTeam/HeroTeamConfigurationSO.cs.meta
  Assets/Code/Scripts/Dungeon/DungeonManager.cs
  Assets/Resources/ScriptableObjects/Entities/HeroTeamConfiguration.asset
  Assets/Resources/ScriptableObjects/Entities/HeroTeamConfiguration.asset.meta
Labels: feature

#221 feat(city-situations): situations can be replayed or not
  Assets/Art/UI/UIKit/Backgrounds/Talent tree/norseVikingPaperBackground.jpg.meta
  Assets/Code/Scripts/City/SituationsController.cs
  Assets/Code/Scripts/City/UI/CityMenuController.cs
  Assets/Code/Scripts/City/UI/CitySituationsMenuController.cs
  Assets/Code/Scripts/Core/Cities/CitySituations/ACitySituationSO.cs
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueSOEditor.cs
  Assets/Level/UI/City/CitySituationsMenu.uxml
  Assets/Level/UI/City/CityStyles.uss
  Assets/Level/UI/City/SituationTemplate.uxml
  Assets/Resources/ScriptableObjects/Entities/HeroTeamConfiguration.asset
  Assets/Resources/ScriptableObjects/InterestPoints/Cities/Sovengard/Situations/ManBuildingDrakkar/SovengardCityDialogueSituation.asset
  Assets/Resources/ScriptableObjects/Quests/ExampleActionsQuest/ExampleActionsQuest2.asset
Labels: feature

#226 feat(tavern): tavern really withdraw stycas
  Assets/Code/Scripts/City/UI/TavernDialogController.cs
  Assets/Level/UI/City/CityStyles.uss
  Assets/Level/UI/City/TavernDialog.uxml
  Assets/Level/UI/Kingdom/EnterCityPanel.uss
  Assets/Level/UI/Kingdom/EnterCityPanel.uxml
  Assets/Level/UI/Kingdom/EnterDungeonPanel.uss
  Assets/Level/UI/Kingdom/EnterDungeonPanel.uxml
Labels: feature

#237 feat/FFS 480 player can use consumables
  Assets/Code/Scripts/Core/Fight/FighterConfigurationSO.cs
  Assets/Code/Scripts/Core/InventorySystem/AConsumable.cs
  Assets/Code/Scripts/Core/InventorySystem/Inventory.cs
  Assets/Code/Scripts/Core/InventorySystem/InventorySlot.cs
  Assets/Code/Scripts/Core/InventorySystem/ItemSO.cs
  Assets/Code/Scripts/Core/UI/ItemSlotContainerUIController.cs
  Assets/Code/Scripts/Core/UI/ItemSlotContainerUIController.cs.meta
  Assets/Code/Scripts/Core/UI/ProgressBarUIController.cs
  Assets/Code/Scripts/Fight/Controllers/PlayerController.cs
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/FightersGenerator.cs
  Assets/Code/Scripts/Fight/Inventory/ConsumableSO.cs
  Assets/Code/Scripts/Fight/UI/AbilitiesBarController.cs
  Assets/Code/Scripts/Fight/UI/ConsumablesUIController.cs
  Assets/Code/Scripts/Fight/UI/ConsumablesUIController.cs.meta
  Assets/Code/Scripts/Fight/UI/FighterActionPanelController.cs
  Assets/Code/Scripts/InventorySystem/UI/BookInventoryMenuUIController.cs
  Assets/Code/Scripts/InventorySystem/UI/InventoryBagPanelUIController.cs
  Assets/Code/Scripts/InventorySystem/UI/InventoryEquippedPanelUIController.cs
  Assets/Level/Scenes/FightScene.unity
  Assets/Level/UI/Components/ProgressBar.uxml
  Assets/Level/UI/Fight/AllyDiamondProgress.uxml
  Assets/Level/UI/Fight/ConsumableSlot.uxml
  Assets/Level/UI/Fight/ConsumableSlot.uxml.meta
  Assets/Level/UI/Fight/FightScenePanel.uss
  Assets/Level/UI/Fight/FightScenePanel.uxml
  Assets/Level/UI/Fight/TimelineCharacterContainer.uxml
  Assets/Level/UI/Inventory/InventoryEquippedPanel.uxml
  Assets/Level/UI/Inventory/inventory.uss
  Assets/Resources/ScriptableObjects/Entities/Hero/HeroFighterConfiguration.asset
Labels: feature

#235 feat(fight-ui): status details panel displayed on mouse hover
  Assets/Code/Scripts/Core/Fight/FighterConfigurationSO.cs
  Assets/Code/Scripts/Core/InventorySystem/AConsumable.cs
  Assets/Code/Scripts/Core/InventorySystem/Inventory.cs
  Assets/Code/Scripts/Core/InventorySystem/InventorySlot.cs
  Assets/Code/Scripts/Core/InventorySystem/ItemSO.cs
  Assets/Code/Scripts/Core/UI/ItemSlotContainerUIController.cs
  Assets/Code/Scripts/Core/UI/ItemSlotContainerUIController.cs.meta
  Assets/Code/Scripts/Core/UI/ProgressBarUIController.cs
  Assets/Code/Scripts/Fight/Controllers/PlayerController.cs
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/FightersGenerator.cs
  Assets/Code/Scripts/Fight/Inventory/ConsumableSO.cs
  Assets/Code/Scripts/Fight/Statuses/AStatus.cs
  Assets/Code/Scripts/Fight/Statuses/EStatusTriggerTime.cs
  Assets/Code/Scripts/Fight/UI/AbilitiesBarController.cs
  Assets/Code/Scripts/Fight/UI/ConsumablesUIController.cs
  Assets/Code/Scripts/Fight/UI/ConsumablesUIController.cs.meta
  Assets/Code/Scripts/Fight/UI/FighterActionPanelController.cs
  Assets/Code/Scripts/Fight/UI/FightersOrderTimelineController.cs
  Assets/Code/Scripts/Fight/UI/StatusDetailsPanelUIController.cs
  Assets/Code/Scripts/Fight/UI/StatusDetailsPanelUIController.cs.meta
  Assets/Code/Scripts/Fight/UI/TimelineCharacterUIController.cs
  Assets/Code/Scripts/InventorySystem/UI/BookInventoryMenuUIController.cs
  Assets/Code/Scripts/InventorySystem/UI/InventoryBagPanelUIController.cs
  Assets/Code/Scripts/InventorySystem/UI/InventoryEquippedPanelUIController.cs
  Assets/Level/Scenes/FightScene.unity
  Assets/Level/UI/Components/ProgressBar.uxml
  Assets/Level/UI/Fight/AllyDiamondProgress.uxml
  Assets/Level/UI/Fight/ConsumableSlot.uxml
  Assets/Level/UI/Fight/ConsumableSlot.uxml.meta
  Assets/Level/UI/Fight/FightScenePanel.uss
  Assets/Level/UI/Fight/FightScenePanel.uxml
  Assets/Level/UI/Fight/TimelineCharacterContainer.uxml
  Assets/Level/UI/Fight/TimelinePanel.uxml
  Assets/Level/UI/FontAssets/MorrisRomanBlack SDF.asset
  Assets/Level/UI/Inventory/InventoryEquippedPanel.uxml
  Assets/Level/UI/Inventory/inventory.uss
  Assets/Resources/ScriptableObjects/Entities/Hero/HeroFighterConfiguration.asset
  Assets/Resources/ScriptableObjects/Fight/Abilities/ActiveAbilities/ExampleFireSpell.asset
Labels: feature

#234 feat(fight-ui): character life displayed in timeline + unique resistance panel
  Assets/Code/Scripts/Core/Fight/FighterConfigurationSO.cs
  Assets/Code/Scripts/Core/InventorySystem/AConsumable.cs
  Assets/Code/Scripts/Core/InventorySystem/Inventory.cs
  Assets/Code/Scripts/Core/InventorySystem/InventorySlot.cs
  Assets/Code/Scripts/Core/InventorySystem/ItemSO.cs
  Assets/Code/Scripts/Core/UI/ItemSlotContainerUIController.cs
  Assets/Code/Scripts/Core/UI/ItemSlotContainerUIController.cs.meta
  Assets/Code/Scripts/Core/UI/ProgressBarUIController.cs
  Assets/Code/Scripts/Fight/Controllers/PlayerController.cs
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/FightersGenerator.cs
  Assets/Code/Scripts/Fight/Inventory/ConsumableSO.cs
  Assets/Code/Scripts/Fight/Statuses/AStatus.cs
  Assets/Code/Scripts/Fight/Statuses/EStatusTriggerTime.cs
  Assets/Code/Scripts/Fight/UI/AbilitiesBarController.cs
  Assets/Code/Scripts/Fight/UI/ConsumablesUIController.cs
  Assets/Code/Scripts/Fight/UI/ConsumablesUIController.cs.meta
  Assets/Code/Scripts/Fight/UI/FighterActionPanelController.cs
  Assets/Code/Scripts/Fight/UI/FighterResistancesPanelController.cs
  Assets/Code/Scripts/Fight/UI/FightersOrderTimelineController.cs
  Assets/Code/Scripts/Fight/UI/StatusDetailsPanelUIController.cs
  Assets/Code/Scripts/Fight/UI/StatusDetailsPanelUIController.cs.meta
  Assets/Code/Scripts/Fight/UI/TimelineCharacterUIController.cs
  Assets/Code/Scripts/InventorySystem/UI/BookInventoryMenuUIController.cs
  Assets/Code/Scripts/InventorySystem/UI/InventoryBagPanelUIController.cs
  Assets/Code/Scripts/InventorySystem/UI/InventoryEquippedPanelUIController.cs
  Assets/Level/Scenes/FightScene.unity
  Assets/Level/UI/Components/ProgressBar.uxml
  Assets/Level/UI/Fight/AllyDiamondProgress.uxml
  Assets/Level/UI/Fight/ConsumableSlot.uxml
  Assets/Level/UI/Fight/ConsumableSlot.uxml.meta
  Assets/Level/UI/Fight/FightScenePanel.uss
  Assets/Level/UI/Fight/FightScenePanel.uxml
  Assets/Level/UI/Fight/TimelineCharacterContainer.uxml
  Assets/Level/UI/Fight/TimelinePanel.uxml
  Assets/Level/UI/FontAssets/MorrisRomanBlack SDF.asset
  Assets/Level/UI/Inventory/InventoryEquippedPanel.uxml
  Assets/Level/UI/Inventory/inventory.uss
  Assets/Resources/ScriptableObjects/Entities/Hero/HeroFighterConfiguration.asset
  Assets/Resources/ScriptableObjects/Fight/Abilities/ActiveAbilities/ExampleFireSpell.asset
Labels: feature

#233 feat(fight-ui): action panel redone + fix suicide bug & return to kingdom by default
  Assets/Code/Scripts/Core/Fight/FighterConfigurationSO.cs
  Assets/Code/Scripts/Core/GameState/Fight/EFightOrigin.cs
  Assets/Code/Scripts/Core/InventorySystem/AConsumable.cs
  Assets/Code/Scripts/Core/InventorySystem/Inventory.cs
  Assets/Code/Scripts/Core/InventorySystem/InventorySlot.cs
  Assets/Code/Scripts/Core/InventorySystem/ItemSO.cs
  Assets/Code/Scripts/Core/UI/ItemSlotContainerUIController.cs
  Assets/Code/Scripts/Core/UI/ItemSlotContainerUIController.cs.meta
  Assets/Code/Scripts/Core/UI/ProgressBarUIController.cs
  Assets/Code/Scripts/Fight/Abilities/ActiveAbilitySO.cs
  Assets/Code/Scripts/Fight/Controllers/PlayerController.cs
  Assets/Code/Scripts/Fight/FightManager.cs
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Fight/FightersGenerator.cs
  Assets/Code/Scripts/Fight/Inventory/ConsumableSO.cs
  Assets/Code/Scripts/Fight/Statuses/AStatus.cs
  Assets/Code/Scripts/Fight/Statuses/EStatusTriggerTime.cs
  Assets/Code/Scripts/Fight/UI/AbilitiesBarController.cs
  Assets/Code/Scripts/Fight/UI/AbilitiesBarController.cs.meta
  Assets/Code/Scripts/Fight/UI/ConsumablesUIController.cs
  Assets/Code/Scripts/Fight/UI/ConsumablesUIController.cs.meta
  Assets/Code/Scripts/Fight/UI/FighterActionPanelController.cs
  Assets/Code/Scripts/Fight/UI/FighterInfosBarController.cs
  Assets/Code/Scripts/Fight/UI/FighterProgressBarsController.cs
  Assets/Code/Scripts/Fight/UI/FighterResistancesPanelController.cs
  Assets/Code/Scripts/Fight/UI/FightersOrderTimelineController.cs
  Assets/Code/Scripts/Fight/UI/RoundsCountLabelController.cs
  Assets/Code/Scripts/Fight/UI/RoundsCountLabelController.cs.meta
  Assets/Code/Scripts/Fight/UI/StatusDetailsPanelUIController.cs
  Assets/Code/Scripts/Fight/UI/StatusDetailsPanelUIController.cs.meta
  Assets/Code/Scripts/Fight/UI/TeamMatesPanelController.cs
  Assets/Code/Scripts/Fight/UI/TeamMatesPanelController.cs.meta
  Assets/Code/Scripts/Fight/UI/TimelineCharacterUIController.cs
  Assets/Code/Scripts/InventorySystem/UI/BookInventoryMenuUIController.cs
  Assets/Code/Scripts/InventorySystem/UI/InventoryBagPanelUIController.cs
  Assets/Code/Scripts/InventorySystem/UI/InventoryEquippedPanelUIController.cs
  Assets/Level/Scenes/DefaultSceneTemplate.scenetemplate
  Assets/Level/Scenes/FightScene.unity
  Assets/Level/UI/Components/ProgressBar.uxml
  Assets/Level/UI/Components/RoundProgress.uxml
  Assets/Level/UI/Components/RoundProgress.uxml.meta
  Assets/Level/UI/Fight/AllyDiamondProgress.uxml
  Assets/Level/UI/Fight/AllyDiamondProgress.uxml.meta
  Assets/Level/UI/Fight/ConsumableSlot.uxml
  Assets/Level/UI/Fight/ConsumableSlot.uxml.meta
  Assets/Level/UI/Fight/FightScenePanel.uss
  Assets/Level/UI/Fight/FightScenePanel.uxml
  Assets/Level/UI/Fight/FighteInfosBar.uxml
  Assets/Level/UI/Fight/TimelineCharacterContainer.uxml
  Assets/Level/UI/Fight/TimelinePanel.uxml
  Assets/Level/UI/FontAssets/MorrisRomanBlack SDF.asset
  Assets/Level/UI/Inventory/InventoryEquippedPanel.uxml
  Assets/Level/UI/Inventory/inventory.uss
  Assets/Resources/ScriptableObjects/Entities/Hero/HeroFighterConfiguration.asset
  Assets/Resources/ScriptableObjects/Fight/Abilities/ActiveAbilities/ExampleFireSpell.asset
  Assets/Resources/ScriptableObjects/InterestPoints/Cities/Sovengard/Situations/ManBuildingDrakkar/SovengardCityDialogueSituation.asset
Labels: bug, feature

#236 Ffs 457 cut fight hex grid with cardinal points
  .gitignore
  Assets/Code/Scripts/Core/FrostfallSaga.Core.asmdef
  Assets/Code/Scripts/Core/GameState/Fight/PreFightData.cs
  Assets/Code/Scripts/Core/GameState/GameStateManager.cs
  Assets/Code/Scripts/Dungeon/DungeonManager.cs
  Assets/Code/Scripts/Dungeon/FrostfallSaga.Dungeon.asmdef
  Assets/Code/Scripts/Fight/FightGridGenerator.cs
  Assets/Code/Scripts/Fight/FightHexGrid.cs
  Assets/Code/Scripts/Fight/FightLoader.cs
  Assets/Code/Scripts/Grid/CellAnalysis.cs
  Assets/Code/Scripts/Grid/CellsNeighbors.cs
  Assets/Code/Scripts/Grid/EditorWindow/CellAnalysisWindow.cs
  Assets/Code/Scripts/Grid/FrostfallSaga.Grid.asmdef
  Assets/Code/Scripts/Kingdom/CellAnalysis.cs
  Assets/Code/Scripts/Kingdom/CellAnalysis.cs.meta
  Assets/Code/Scripts/Kingdom/EditorWindow.meta
  Assets/Code/Scripts/Kingdom/EditorWindow/CellAnalysisWindow.cs
  Assets/Code/Scripts/Kingdom/EditorWindow/CellAnalysisWindow.cs.meta
  Assets/Code/Scripts/Kingdom/FrostfallSaga.Kingdom.asmdef
  Assets/Code/Scripts/Kingdom/KingdomHexGrid.cs
  Assets/Code/Scripts/Kingdom/KingdomToFightTransitioner.cs
  Assets/Code/Scripts/Procedural/PerlinTerrainManager.cs
  Assets/Code/Scripts/Utils/Randomizer.cs
  Assets/Level/Scenes/FightScene.unity
  Assets/Level/Scenes/KingdomScene.unity
  Assets/PolygonParticleFX.meta
  Assets/Resources/Prefabs/Grid/Cell.prefab
  Assets/Resources/Prefabs/Grid/FightCell.prefab
Labels: feature, TO REVIEW ASAP

#238 feat: visual accessibles/blocked && percent of accessibles for inacce…
  Assets/Code/Scripts/Fight/FightGridGenerator.cs
  Assets/Code/Scripts/Grid/Cells/Cell.cs
  Assets/Code/Scripts/Grid/TerrainTypeSO.cs
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeDarkForest.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeForest.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeFrozenDarkForest.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeFrozenForest.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeFrozenMountain.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeFrozenPlain.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeFrozenWater.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeMountain.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypePlain.asset
  Assets/Resources/ScriptableObjects/Grid/Terrain/TerrainTypeWater.asset
Labels: feature, TO REVIEW ASAP

#239 feat: fighters spawn on accessible cell
  Assets/Code/Scripts/Fight/FightGridGenerator.cs
  Assets/Code/Scripts/Fight/FightHexGrid.cs
  Assets/Code/Scripts/Fight/FightManager.cs
  Assets/Level/Scenes/FightScene.unity
Labels: feature, TO REVIEW ASAP
