Repository Nostralys-Studio/FrostfallSaga, pull requests merged in 2025-02, with the labels that each got.

#187 feat(EnterDungeonPanel): simple dungeon enter panel added
  Assets/Art/UI/Illustrations/exampleDungeonBg.jpg
  Assets/Art/UI/Illustrations/exampleDungeonBg.jpg.meta
  Assets/Code/Scripts/Core/Dungeons/DungeonBuildingConfigurationSO.cs
  Assets/Code/Scripts/Kingdom/UI/EnterDungeonPanelController.cs
  Assets/Code/Scripts/Kingdom/UI/EnterDungeonPanelController.cs.meta
  Assets/Level/Scenes/KingdomScene.unity
  Assets/Level/UI/Kingdom/EnterDungeonPanel.uss
  Assets/Level/UI/Kingdom/EnterDungeonPanel.uss.meta
  Assets/Level/UI/Kingdom/EnterDungeonPanel.uxml
  Assets/Level/UI/Kingdom/EnterDungeonPanel.uxml.meta
  Assets/Resources/ScriptableObjects/InterestPoints/Dungeons/RatsewerDungeonBuildingConfiguration.asset
Labels: feature

#189 feat(KingdomToDungeon): transition from kingdom to dungeon scene added
  Assets/Code/Scripts/Core/Dungeons/DungeonBuildingConfigurationSO.cs
  Assets/Code/Scripts/Core/Dungeons/DungeonConfigurationSO.cs
  Assets/Code/Scripts/Core/Dungeons/DungeonConfigurationSO.cs.meta
  Assets/Code/Scripts/Core/EScenesName.cs
  Assets/Code/Scripts/Core/GameState/Dungeon.meta
  Assets/Code/Scripts/Core/GameState/Dungeon/DungeonLoadData.cs
  Assets/Code/Scripts/Core/GameState/Dungeon/DungeonLoadData.cs.meta
  Assets/Code/Scripts/Core/GameState/GameStateManager.cs
  Assets/Code/Scripts/Dungeon.meta
  Assets/Code/Scripts/Dungeon/DungeonManager.cs
  Assets/Code/Scripts/Dungeon/DungeonManager.cs.meta
  Assets/Code/Scripts/Dungeon/FrostfallSaga.Dungeon.asmdef
  Assets/Code/Scripts/Dungeon/FrostfallSaga.Dungeon.asmdef.meta
  Assets/Code/Scripts/Kingdom/CityLoader.cs
  Assets/Code/Scripts/Kingdom/DungeonLoader.cs
  Assets/Code/Scripts/Kingdom/DungeonLoader.cs.meta
  Assets/Level/Scenes/DefaultSceneTemplate.scenetemplate
  Assets/Level/Scenes/DungeonScene.meta
  Assets/Level/Scenes/DungeonScene.unity
  Assets/Level/Scenes/DungeonScene.unity.meta
  Assets/Level/Scenes/DungeonScene/LightingData.asset
  Assets/Level/Scenes/DungeonScene/LightingData.asset.meta
  Assets/Level/Scenes/KingdomScene.unity
  Assets/Resources/ScriptableObjects/InterestPoints/Dungeons/Ratsewer.meta
  Assets/Resources/ScriptableObjects/InterestPoints/Dungeons/Ratsewer/RatsewerDungeonBuildingConfiguration.asset
  Assets/Resources/ScriptableObjects/InterestPoints/Dungeons/Ratsewer/RatsewerDungeonBuildingConfiguration.asset.meta
  Assets/Resources/ScriptableObjects/InterestPoints/Dungeons/Ratsewer/RatsewerDungeonConfiguration.asset
  Assets/Resources/ScriptableObjects/InterestPoints/Dungeons/Ratsewer/RatsewerDungeonConfiguration.asset.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: feature

#190 feat: basic dungeon fights unfolding done
  Assets/Code/Scripts/Core/Dungeons/DungeonConfigurationSO.cs
  Assets/Code/Scripts/Core/Dungeons/DungeonFightConfiguration.cs
  Assets/Code/Scripts/Core/Dungeons/DungeonFightConfiguration.cs.meta
  Assets/Code/Scripts/Core/GameState/Dungeon/DungeonLoadData.cs
  Assets/Code/Scripts/Core/GameState/Dungeon/DungeonState.cs
  Assets/Code/Scripts/Core/GameState/Dungeon/DungeonState.cs.meta
  Assets/Code/Scripts/Core/GameState/Fight/EFightOrigin.cs
  Assets/Code/Scripts/Core/GameState/Fight/EFightOrigin.cs.meta
  Assets/Code/Scripts/Core/GameState/Fight/PreFightData.cs
  Assets/Code/Scripts/Core/GameState/GameStateManager.cs
  Assets/Code/Scripts/Core/HeroTeam/Hero.cs
  Assets/Code/Scripts/Core/HeroTeam/HeroTeam.cs
  Assets/Code/Scripts/Dungeon/DungeonManager.cs
  Assets/Code/Scripts/Fight/FightToNextSceneTransitioner.cs
  Assets/Code/Scripts/Fight/FightToNextSceneTransitioner.cs.meta
  Assets/Code/Scripts/Fight/FightersGenerator.cs
  Assets/Code/Scripts/Fight/PostFightDataGenerator.cs
  Assets/Code/Scripts/Kingdom/DungeonLoader.cs
  Assets/Code/Scripts/Kingdom/KingdomToFightTransitioner.cs
  Assets/Resources/ScriptableObjects/InterestPoints/Dungeons/Ratsewer/RatsewerDungeonBuildingConfiguration.asset
  Assets/Resources/ScriptableObjects/InterestPoints/Dungeons/Ratsewer/RatsewerDungeonConfiguration.asset
Labels: feature

#192 feat(DialogueSystem): data models of dialogue system added + BehaviourTree moved to utils
  Assets/Code/Scripts/BehaviourTree/FrostfallSaga.BehaviourTree.asmdef
  Assets/Code/Scripts/DialogueSystem.meta
  Assets/Code/Scripts/DialogueSystem/DialogueLine.cs
  Assets/Code/Scripts/DialogueSystem/DialogueLine.cs.meta
  Assets/Code/Scripts/DialogueSystem/DialogueParticiantSO.cs
  Assets/Code/Scripts/DialogueSystem/DialogueParticiantSO.cs.meta
  Assets/Code/Scripts/DialogueSystem/DialogueSO.cs
  Assets/Code/Scripts/DialogueSystem/DialogueSO.cs.meta
  Assets/Code/Scripts/DialogueSystem/Editor.meta
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueSOEditor.cs
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueSOEditor.cs.meta
  Assets/Code/Scripts/DialogueSystem/Editor/FrostfallSaga.Editor.Fight.asmref
  Assets/Code/Scripts/DialogueSystem/Editor/FrostfallSaga.Editor.Fight.asmref.meta
  Assets/Code/Scripts/DialogueSystem/FrostfallSaga.DialogueSystem.asmdef
  Assets/Code/Scripts/DialogueSystem/FrostfallSaga.DialogueSystem.asmdef.meta
  Assets/Code/Scripts/Editor/FrostfallSaga.FFSEditor.asmdef
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/DamageTargetAction.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/EndTurnAction.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Actions/MoveToClosestTargetAction.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Checks/CanDamageTargetCheck.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Checks/CanHealTargetCheck.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Checks/CanMoveCheck.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/FBTNode.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/FighterBehaviourTree.cs
  Assets/Code/Scripts/Fight/Controllers/FighterBehaviourTrees/Trees/AggressiveFBT.cs
  Assets/Code/Scripts/Fight/FrostfallSaga.Fight.asmdef
  Assets/Code/Scripts/Utils/Trees.meta
  Assets/Code/Scripts/Utils/Trees/BehaviourTree.meta
  Assets/Code/Scripts/Utils/Trees/BehaviourTree/BTree.cs
  Assets/Code/Scripts/Utils/Trees/BehaviourTree/BTree.cs.meta
  Assets/Code/Scripts/Utils/Trees/BehaviourTree/Node.cs
  Assets/Code/Scripts/Utils/Trees/BehaviourTree/Node.cs.meta
  Assets/Code/Scripts/Utils/Trees/BehaviourTree/Selector.cs
  Assets/Code/Scripts/Utils/Trees/BehaviourTree/Selector.cs.meta
  Assets/Code/Scripts/Utils/Trees/BehaviourTree/Sequence.cs
  Assets/Code/Scripts/Utils/Trees/BehaviourTree/Sequence.cs.meta
  Assets/Code/Scripts/Utils/Trees/GeneralPurposeTree.meta
  Assets/Code/Scripts/Utils/Trees/GeneralPurposeTree/TreeNode.cs
  Assets/Code/Scripts/Utils/Trees/GeneralPurposeTree/TreeNode.cs.meta
  Assets/Resources/ScriptableObjects/Dialogues.meta
  Assets/Resources/ScriptableObjects/Dialogues/DialogueExample.asset
  Assets/Resources/ScriptableObjects/Dialogues/DialogueExample.asset.meta
  Assets/Resources/ScriptableObjects/Dialogues/Participants.meta
  Assets/Resources/ScriptableObjects/Dialogues/Participants/HeroDialogueParticipant.asset
  Assets/Resources/ScriptableObjects/Dialogues/Participants/HeroDialogueParticipant.asset.meta
  Assets/Resources/ScriptableObjects/Dialogues/Participants/SkeletonDialogueParticipant.asset
  Assets/Resources/ScriptableObjects/Dialogues/Participants/SkeletonDialogueParticipant.asset.meta
Labels: feature, refactoring

#193 feat(dialogues): basic dialog ui template added
  Assets/Level/UI/Dialogues.meta
  Assets/Level/UI/Dialogues/DialogueTemplate.uss
  Assets/Level/UI/Dialogues/DialogueTemplate.uss.meta
  Assets/Level/UI/Dialogues/DialogueTemplate.uxml
  Assets/Level/UI/Dialogues/DialogueTemplate.uxml.meta
  Assets/Level/UI/FontAssets/MorrisRomanBlack SDF.asset
Labels: feature

#194 feat(DialogueUIProcessor): dialogues can be processed through ui controller
  Assets/Code/Scripts/DialogueSystem/DialogueTestLauncher.cs
  Assets/Code/Scripts/DialogueSystem/DialogueTestLauncher.cs.meta
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueSOEditor.cs
  Assets/Code/Scripts/DialogueSystem/UI.meta
  Assets/Code/Scripts/DialogueSystem/UI/DialogueUIProcessor.cs
  Assets/Code/Scripts/DialogueSystem/UI/DialogueUIProcessor.cs.meta
  Assets/Code/Scripts/Utils/Trees/GeneralPurposeTree/TreeNode.cs
  Assets/Level/Scenes/DevScenes.meta
  Assets/Level/Scenes/DevScenes/AbilityAnimationExecutorsTest.unity
  Assets/Level/Scenes/DevScenes/AbilityAnimationExecutorsTest.unity.meta
  Assets/Level/Scenes/DevScenes/DevHub.unity
  Assets/Level/Scenes/DevScenes/DevHub.unity.meta
  Assets/Level/Scenes/DevScenes/DialogueTestScene.unity
  Assets/Level/Scenes/DevScenes/DialogueTestScene.unity.meta
  Assets/Level/UI/Dialogues/AnswerContainer.uxml
  Assets/Level/UI/Dialogues/AnswerContainer.uxml.meta
  Assets/Level/UI/Dialogues/DialogueTemplate.uss
  Assets/Level/UI/Dialogues/DialogueTemplate.uxml
  Assets/Level/UI/FontAssets/MorrisRomanBlack SDF.asset
  ProjectSettings/EditorBuildSettings.asset
Labels: feature, TO REVIEW ASAP

#178 Feat/ffs 398 UI sounds enum
  Assets/Code/Scripts/Audio/AudioManager.cs
  Assets/Code/Scripts/Audio/SoundsEnums.cs
  Assets/Code/Scripts/Audio/SoundsEnums.cs.meta
  Assets/Code/Scripts/Audio/UI.meta
  Assets/Code/Scripts/Audio/UI/UIAudioClipSelector.cs
  Assets/Code/Scripts/Audio/UI/UIAudioClipSelector.cs.meta
  Assets/Code/Scripts/Audio/UI/UIAudioClipsConfig.cs
  Assets/Code/Scripts/Audio/UI/UIAudioClipsConfig.cs.meta
  Assets/Code/Tests/PlayModeTests/Audio/AudioManagerTests.cs
  Assets/Level/Scenes/KingdomScene.unity
  Assets/Resources/Prefabs/Audio/2D_AudioSource.prefab
  Assets/Resources/ScriptableObjects/Audio.meta
  Assets/Resources/ScriptableObjects/Audio/UIAudioClipsConfig.asset
  Assets/Resources/ScriptableObjects/Audio/UIAudioClipsConfig.asset.meta
Labels: feature

#196 feat(situations): city can have situations that launches a dialogue
  Assets/Art/UI/Illustrations/SovengardManBuildingDrakkarDialogueIllustration.png
  Assets/Art/UI/Illustrations/SovengardManBuildingDrakkarDialogueIllustration.png.meta
  Assets/Code/Scripts/City/SituationsController.cs
  Assets/Code/Scripts/City/SituationsController.cs.meta
  Assets/Code/Scripts/City/UI/CityMenuController.cs
  Assets/Code/Scripts/City/UI/CitySituationsMenuController.cs
  Assets/Code/Scripts/City/UI/CitySituationsMenuController.cs.meta
  Assets/Code/Scripts/Core/Cities/CitySituations.meta
  Assets/Code/Scripts/Core/Cities/CitySituations/ACitySituationSO.cs
  Assets/Code/Scripts/Core/Cities/CitySituations/ACitySituationSO.cs.meta
  Assets/Code/Scripts/Core/Cities/CitySituations/CityDialogueSituation.cs
  Assets/Code/Scripts/Core/Cities/CitySituations/CityDialogueSituation.cs.meta
  Assets/Code/Scripts/Core/Cities/InCityConfigurationSO.cs
  Assets/Code/Scripts/Core/Cities/InCityConfigurationSO.cs.meta
  Assets/Code/Scripts/Core/Cities/TavernConfiguration.cs
  Assets/Code/Scripts/Core/Dialogues.meta
  Assets/Code/Scripts/Core/Dialogues/DialogueLine.cs
  Assets/Code/Scripts/Core/Dialogues/DialogueLine.cs.meta
  Assets/Code/Scripts/Core/Dialogues/DialogueParticiantSO.cs
  Assets/Code/Scripts/Core/Dialogues/DialogueParticiantSO.cs.meta
  Assets/Code/Scripts/Core/Dialogues/DialogueSO.cs
  Assets/Code/Scripts/Core/Dialogues/DialogueSO.cs.meta
  Assets/Code/Scripts/Core/Dialogues/DialogueUIProcessor.cs
  Assets/Code/Scripts/Core/Dialogues/DialogueUIProcessor.cs.meta
  Assets/Code/Scripts/DialogueSystem/DialogueTestLauncher.cs
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueSOEditor.cs
  Assets/Code/Scripts/DialogueSystem/FrostfallSaga.DialogueSystem.asmdef
  Assets/Code/Scripts/Editor/FrostfallSaga.FFSEditor.asmdef
  Assets/Level/Scenes/CityScene.unity
  Assets/Level/UI/City/CityMainMenu.uxml
  Assets/Level/UI/City/CitySituationsMenu.uxml
  Assets/Level/UI/City/CitySituationsMenu.uxml.meta
  Assets/Level/UI/City/CityStyles.uss
  Assets/Level/UI/City/CityStyles.uss.meta
  Assets/Level/UI/City/SituationTemplate.uxml
  Assets/Level/UI/City/SituationTemplate.uxml.meta
  Assets/Level/UI/Dialogues/DialogueTemplate.uss
  Assets/Resources/ScriptableObjects/InterestPoints/Cities/Sovengard/Situations.meta
  Assets/Resources/ScriptableObjects/InterestPoints/Cities/Sovengard/Situations/ManBuildingDrakkar.meta
  Assets/Resources/ScriptableObjects/InterestPoints/Cities/Sovengard/Situations/ManBuildingDrakkar/SovengardCityDialogueSituation.asset
  Assets/Resources/ScriptableObjects/InterestPoints/Cities/Sovengard/Situations/ManBuildingDrakkar/SovengardCityDialogueSituation.asset.meta
  Assets/Resources/ScriptableObjects/InterestPoints/Cities/Sovengard/Situations/ManBuildingDrakkar/SovengardManBuildingDrakkarDialogue.asset
  Assets/Resources/ScriptableObjects/InterestPoints/Cities/Sovengard/Situations/ManBuildingDrakkar/SovengardManBuildingDrakkarDialogue.asset.meta
  Assets/Resources/ScriptableObjects/InterestPoints/Cities/Sovengard/SovengardInCityConfiguration.asset
Labels: feature

#198 refactor: kingdom manager only defines one interest point encounter event to avoid code duplication
  Assets/Code/Scripts/Kingdom/KingdomManager.cs
  Assets/Code/Scripts/Kingdom/UI/EnterCityPanelController.cs
  Assets/Code/Scripts/Kingdom/UI/EnterDungeonPanelController.cs
Labels: refactoring

#199 Feat/ffs 413 custom dialogue editor
  Assets/Code/Scripts/Core/Dialogues/DialogueLine.cs
  Assets/Code/Scripts/Core/Dialogues/DialogueUIProcessor.cs
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueGraphView.cs
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueGraphView.cs.meta
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueNode.cs
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueNode.cs.meta
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueSOEditor.cs
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueWindowEditor.cs
  Assets/Code/Scripts/DialogueSystem/Editor/DialogueWindowEditor.cs.meta
  Assets/Code/Scripts/Utils/Trees/GeneralPurposeTree/TreeNode.cs
  Assets/Resources/ScriptableObjects/Dialogues/DialogueExample.asset
  Assets/Resources/ScriptableObjects/Dialogues/DialogueExample.asset.meta
Labels: devtool, TO REVIEW ASAP

#217 feat: interestsPoints have cells now
  Assets/Code/Scripts/Kingdom/KingdomCell.cs
  Assets/Code/Scripts/Kingdom/KingdomGridGenerator.cs
  Assets/Code/Scripts/Kingdom/KingdomHexGrid.cs
  Assets/Code/Scripts/Kingdom/KingdomLoader.cs
  Assets/Level/Scenes/KingdomScene.unity
Labels: feature

#200 Fix/hero team health consistency
  Assets/Code/Scripts/Core/HeroTeam/HeroTeam.cs
  Assets/Code/Scripts/Dungeon/DungeonManager.cs
  Assets/Code/Scripts/Fight/Fighter/Fighter.cs
  Assets/Code/Scripts/Kingdom/KingdomLoader.cs
  Assets/Code/Scripts/Kingdom/KingdomToFightTransitioner.cs
Labels: bug

#201 feat(quests): quest system with two types of quests added
  Assets/Code/Scripts/Core/Quests.meta
  Assets/Code/Scripts/Core/Quests/AQuestAction.cs
  Assets/Code/Scripts/Core/Quests/AQuestAction.cs.meta
  Assets/Code/Scripts/Core/Quests/AQuestSO.cs
  Assets/Code/Scripts/Core/Quests/AQuestSO.cs.meta
  Assets/Code/Scripts/Core/Quests/ActionsQuestSO.cs
  Assets/Code/Scripts/Core/Quests/ActionsQuestSO.cs.meta
  Assets/Code/Scripts/Core/Quests/EQuestType.cs
  Assets/Code/Scripts/Core/Quests/EQuestType.cs.meta
  Assets/Code/Scripts/Core/Quests/QuestEnding.cs
  Assets/Code/Scripts/Core/Quests/QuestEnding.cs.meta
  Assets/Code/Scripts/Core/Quests/QuestStep.cs
  Assets/Code/Scripts/Core/Quests/QuestStep.cs.meta
  Assets/Code/Scripts/Core/Quests/QuestStepActions.cs
  Assets/Code/Scripts/Core/Quests/QuestStepActions.cs.meta
  Assets/Code/Scripts/Core/Quests/StepsQuestSO.cs
  Assets/Code/Scripts/Core/Quests/StepsQuestSO.cs.meta
  Assets/Code/Scripts/Fight/QuestActions.meta
  Assets/Code/Scripts/Fight/QuestActions/WinFightQuestAction.cs
  Assets/Code/Scripts/Fight/QuestActions/WinFightQuestAction.cs.meta
  Assets/Code/Scripts/Kingdom/QuestActions.meta
  Assets/Code/Scripts/Kingdom/QuestActions/EncounterEnemiesGroupQuestAction.cs
  Assets/Code/Scripts/Kingdom/QuestActions/EncounterEnemiesGroupQuestAction.cs.meta
  Assets/Code/Scripts/Quests.meta
  Assets/Code/Scripts/Quests/Editor.meta
  Assets/Code/Scripts/Quests/Editor/AQuestActionDrawer.cs
  Assets/Code/Scripts/Quests/Editor/AQuestActionDrawer.cs.meta
  Assets/Code/Scripts/Quests/Editor/ActionsQuestSOEditor.cs
  Assets/Code/Scripts/Quests/Editor/ActionsQuestSOEditor.cs.meta
  Assets/Code/Scripts/Quests/Editor/QuestStepActionsEditor.cs
  Assets/Code/Scripts/Quests/Editor/QuestStepActionsEditor.cs.meta
  Assets/Code/Scripts/Quests/Editor/StepsQuestSOEditor.cs
  Assets/Code/Scripts/Quests/Editor/StepsQuestSOEditor.cs.meta
  Assets/Code/Scripts/Quests/FrostfallSaga.Quests.asmdef
  Assets/Code/Scripts/Quests/FrostfallSaga.Quests.asmdef.meta
  Assets/Code/Scripts/Quests/UI.meta
  Assets/Code/Scripts/Utils/Trees/GeneralPurposeTree/TreeNode.cs
  Assets/Resources/ScriptableObjects/Quests.meta
  Assets/Resources/ScriptableObjects/Quests/ExampleActionsQuest.meta
  Assets/Resources/ScriptableObjects/Quests/ExampleActionsQuest/ExampleActionsQuest.asset
  Assets/Resources/ScriptableObjects/Quests/ExampleActionsQuest/ExampleActionsQuest.asset.meta
  Assets/Resources/ScriptableObjects/Quests/ExampleStepsQuest.meta
  Assets/Resources/ScriptableObjects/Quests/ExampleStepsQuest/ExampleQuestStepActions.asset
  Assets/Resources/ScriptableObjects/Quests/ExampleStepsQuest/ExampleQuestStepActions.asset.meta
  Assets/Resources/ScriptableObjects/Quests/ExampleStepsQuest/StepsQuest.asset
  Assets/Resources/ScriptableObjects/Quests/ExampleStepsQuest/StepsQuest.asset.meta
Labels: feature, TO REVIEW ASAP
